### ISSUE TITLE
Template building -- preview Actions outputs

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-web-app#1007]
@andreievg -- Nicole and I both think this should be top priority, as it's currently far too easy to mess up configs by not ensuring the action queries are actually pointing to the things we expect them to.

We have the nice little "Preview query" (lightning bolt) function for Form Elements, but we really need it for Actions too. It's currently there, but doesnt' take into account form responses (i.e. applicationData). It's becoming increasingly clear that we need to be able to see the result of the Action while in the Template Builder. 

Hopefully it's not a big job to generate application data for the "dummy" application so we can test Action queries?

(This might require a call to back-end, since usually back-end generates applicationData for Actions. I can quite easily setup an endpoint for "generateApplicationData" if that will help?)

**Comment by andreievg** [comment]
For evaluation results (for lightning bolt to work):

evaluator element in form:

https://github.com/openmsupply/application-manager-web-app/blob/ef40534bb8714285ca8566dcb0fdab8dc346deaf/src/containers/TemplateBuilder/template/Form/ElementConfig.tsx#L207-L213

evaluator element in action:

https://github.com/openmsupply/application-manager-web-app/blob/ef40534bb8714285ca8566dcb0fdab8dc346deaf/src/containers/TemplateBuilder/template/Actions/ActionConfig.tsx#L119-L123

Notice fullStructure is missing in actions.

Basically need to provide application data from server for this application (and pass it to that component), can probably do this when action config is opened:

https://github.com/openmsupply/application-manager-web-app/blob/ef40534bb8714285ca8566dcb0fdab8dc346deaf/src/containers/TemplateBuilder/template/Actions/ActionConfig.tsx#L49-L53

Can do it more efficiently but would require getting the application data downstream, probably a context when action page is loaded at:https://github.com/openmsupply/application-manager-web-app/blob/ef40534bb8714285ca8566dcb0fdab8dc346deaf/src/containers/TemplateBuilder/template/Actions/Actions.tsx and then use that context state in ActionConfig.

I think you are the most familiar with action and trigger code on back end and the application data generation that is used in action evaluation, so would assume the back end bit for this should be straight forward for you.

For actions that need review data ? That would require a bit more thought, let me know if that's important, we can spec it out a bit later

**Comment by CarlosNZ** [comment]
Great, thanks for that. Will try and whip it up this week, will discuss with Nicole.
> For actions that need review data ? That would require a bit more thought, let me know if that's important, we can spec it out a bit later

Yeah, that would be annoying cos at a minimum you'd have to provide a "review" for the dummy application, which would be a real hassle. I think application responses should cover most cases now though. The main problem area we keep running into is making sure the outcomes (from ModifyRecord) get the correct data from responses -- it's way too easy to make tiny errors and you don't notice until going through the whole application procedure till approval.
