### ISSUE TITLE
Copyright year to auto-update

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/application-manager-web-app#1026]
The copyright year is currently showing 2020 - can we make this auto-update to the current year?

![image](https://user-images.githubusercontent.com/19318937/136908624-5e8dce11-975a-423a-aecd-044e289182a6.png)

**Comment by CarlosNZ** [comment]
Oh yeah, duh! Thanks, and done:

https://github.com/openmsupply/application-manager-web-app/pull/1027
