### ISSUE TITLE
Redirection to the summary in case the application is submitted

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#103]

**Comment by CarlosNZ** [comment]
Another re-direction this needs is for the application base URL:
i.e. if we try and go to `/applications/689/`:
 - If "Draft", redirect to `/applications/689/S1/page1` (or maybe the last page edited)
 - If "Completed" (etc.), redirect to `/applications/689/summary`

**Comment by CarlosNZ** [comment]
This seems like a duplicate of #68, isn't it, @nmadruga ? Shall we close?
