### ISSUE TITLE
Bug: Showing the Add icon  in the summary page for static text

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#1039]

**Comment by CarlosNZ** [comment]
![Screen Shot 2022-02-17 at 9 54 27 AM](https://user-images.githubusercontent.com/5456533/154355316-9b5ffd3d-9bc8-4702-95eb-df25a1038f2a.png)

This seems to be fixed? Okay to close @nmadruga ?

**Comment by nmadruga** [comment]
Yes, I'm closing this issue now. Thanks @CarlosNZ
