### ISSUE TITLE
Bug: Can assign a completed application sometimes

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-web-app#1078]
Not sure what condition this occurs, or if it can be fixed with a fresh "regenerateReviewAssignments", just flagging it here so we're aware: application is assignable even though it's completed/approved:
![Screen Shot 2021-12-16 at 1 02 28 PM](https://user-images.githubusercontent.com/5456533/146283945-cf08ec18-ffeb-483b-9f5c-c098873f660b.png)

**Comment by CarlosNZ** [comment]
Do we know if this is still happening? I haven't seen it in a while.

**Comment by nmadruga** [comment]
I haven't seen this either. I'll close it : )
