### ISSUE TITLE
New Review home page: Progress bar

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#1084]
Separate work into building the query of Graphql that gives all stages of an application (regardless of user's permission to review/assign) and defining the status of each stage (considering multiple levels) in a single query.

Then use this information to draw the Progress component at the top
For each stage should display the icon & label (of the Stage) in color, and follow the same icon/colour key as the application progress bar (left side bar):
![Screen Shot 2022-01-20 at 3 04 38 PM](https://user-images.githubusercontent.com/5456533/150251822-e19c2f49-af6f-4d6e-a21a-3d46cba05095.png)
- Green (with Tick ✅ icon): In progress or Missing levels to complete
- White (hollow): Stage not yet reached
- Blue dot (in circle): In progress (i.e. we're at this stage, either applicant or reviewer could be working on it)
- Pink (with X icon): application was rejected at this stage (this is different to application progress bar, but still implies a "negative" state)

Use this as a reference for the progress component:
<img width="1660" alt="Screen Shot 2022-01-19 at 3 04 49 PM" src="https://user-images.githubusercontent.com/16461988/150247890-2e5f2741-3815-4670-a339-7c56abe8832c.png">

**Comment by CarlosNZ** [comment]
@nmadruga -- thinking of trying this package for the progress bar: https://www.npmjs.com/package/react-minimal-progress-steps

Should be a lot simpler than trying to make our own from scratch. Seem okay to you?

I'll do a quick version and see how it goes.

**Comment by CarlosNZ** [comment]
Or maybe this one: https://www.npmjs.com/package/react-stepz

**Comment by CarlosNZ** [comment]
Or... https://www.npmjs.com/package/react-form-stepper

**Comment by CarlosNZ** [comment]
Ended up with this one: https://www.npmjs.com/package/react-progress-stepper

Seems the most suitable to our needs and is pretty minimal and easy to customise:
<img width="783" alt="Screen Shot 2022-01-27 at 8 31 18 AM" src="https://user-images.githubusercontent.com/5456533/151233325-13c729c4-955c-47d2-82b9-0141337a985f.png">
