### ISSUE TITLE
Assignment bug -- problem when reassigning not all the sections to a reviewer who previously was assigned to all sections

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-web-app#1109]
See this comment for description of the problem: https://github.com/openmsupply/application-manager-web-app/pull/1097#pullrequestreview-878046732

The problem is that the process/mutation to change the assignment doesn't check sections. So when reviewer is re-assigned for some sections, it just marks their whole review_assignment record as "AVAILABLE" again.

What it should do is check if some sections are still assigned, and reallocate review-question-assignments accordingly.

**Comment by nmadruga** [comment]
Something else - noted while working on un-assignment mutation update PR #1124 - is that we previously were not removing `reviewQuestionAssignments` which were linked to the `reviewAssignment` being unassigned. That has been done now as part of the refered PR, but would need some added logic when we want to do a partial unassignment, so only reviewQuestionAssignments belonging to certain sections should be removed also.
