### ISSUE TITLE
Bug: Re-assignment shouldn't be allowed for changing 2 assignments at the same time

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#1132]
The problem started to happen after the changes were made to add a new **Submit** button on the Reassignment tab to make a single-mutation with all the sections re-assigned. The problem is that we only deal with unassigning from **one** review_assignment, and not many - although we allow this on the Front-end and the result is the bug described below:

This example uses the snapshot `dev/snapshots/__just_before_assignment` to make this easy to recreate. And the problem here has been mentioned on a [comment in the PR](https://github.com/openmsupply/application-manager-web-app/pull/1128#discussion_r818167355) for removing the reviewQuestionAssignments table and allowing for actually unassigning only sections (instead of the whole review) from a review_assignment.

In this example I have assigned section 1 to **Samanta** and Sections 2 and 3 to **Senior reviewer**:
![Screen Shot 2022-03-03 at 5 09 08 PM](https://user-images.githubusercontent.com/16461988/156495605-33232d1a-4e66-4d23-a894-6508735df604.png)

Now if we try to re-assign both sections 1 and 2 to **Admin** (note these are different review_assignments):
![Screen Shot 2022-03-03 at 5 09 23 PM](https://user-images.githubusercontent.com/16461988/156495603-e12c790e-e06a-47f2-8ddb-b0f738b47a4a.png)

The assignment doesn't show any problems... 
If you are logged as Admin you can see you are assigned to the section and Samanta has been correctly unassigned:
![Screen Shot 2022-03-03 at 5 08 50 PM](https://user-images.githubusercontent.com/16461988/156495606-92e719ec-734b-4feb-aabb-5adc9ee4edb2.png)

Now the problem is, if you logiin as **Senior reviewer** it is **ALSO** showing as they are assigned to Sectioin 2!
![Screen Shot 2022-03-03 at 5 08 37 PM](https://user-images.githubusercontent.com/16461988/156495597-dcbd578f-4b33-4ea3-81a1-7b8a2d7ca313.png)

**Comment by CarlosNZ** [comment]
I think we've made the reassignment process overly complicated by having three different mutations: assignment, unassignment, and re-assignment. This would all be much simpler if there was just one mutation "assignment", and it changed the status field to either "Assigned" or "Available" and updated the "assigned_sections" field if needed.

When you press "Submit", a *single* function deduces which review assignments need to change, and to what. It then just iterates over each review_assignment that needs changing and runs the mutation for each.

We could reduce two hooks and three mutations down to one hook and one mutation, and make the logic a lot simpler in the process.
