### ISSUE TITLE
Block other language from being selected

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#1140]
* On Angola server only allow Portuguese selection for language 
* On the user menu, should also fix the **Not translated string** "Change language"

**Comment by CarlosNZ** [comment]
We can already do this -- just set `enabled: false` in `languages.json`

**Comment by CarlosNZ** [comment]
Can I close it or did you mean something else?

**Comment by nmadruga** [comment]
This is a reminder for our setup in Angola-demo. Check out the Project which this related to. I wasn't sure how much work it would include, so added this issue. But good to know it will be that simple! I'll try to add this today in order to close this issue

**Comment by CarlosNZ** [comment]
Okay, thanks.

FYI -- A while ago I started working on a UI page for `/admin/localisations` but left it for a while to focus on other things. I'll try and finish it off in the next wee while so configuring languages will be even easier!

<img width="505" alt="Screen Shot 2022-03-31 at 9 43 17 AM" src="https://user-images.githubusercontent.com/5456533/160927651-70adc61f-4616-4cd4-8606-cca587ae592b.png">

**Comment by CarlosNZ** [comment]
Just FYI -- this config won't work (i.e. the snapshot won't load the language settings) until this PR is in: https://github.com/openmsupply/application-manager-server/pull/701

**Comment by nmadruga** [comment]
Thanks! Working on getting the version 0.2.0-2 with this change installed on the server and with removed the other languages from the snapshot today
