### ISSUE TITLE
Create login view for user

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#115]
UI - Should be a 2 step login:
* First page where user enters `username` and `password` -> What is aimed for this issue
* Second page where we list user's companies and the user selects a company to login (To be done in another issue!)

**Comment by CarlosNZ** [comment]
>     * Second page where we list user's companies and the user selects a company to login (To be done in another issue!)

Not a biggie, but why not just have the company selector appear on the same page after initial login? Is this something we should get Debbie to weigh in on? (Probably, right?)

But I'm thinking we just change this:
![Screen Shot 2020-11-26 at 12 06 47 PM](https://user-images.githubusercontent.com/5456533/100290304-e5876400-2fdf-11eb-8ccd-f6c59962e37d.png)
into something like this (without loading a new page):
![Screen Shot 2020-11-26 at 12 07 28 PM](https://user-images.githubusercontent.com/5456533/100290355-00f26f00-2fe0-11eb-9e29-7f34339cb59f.png)
