### ISSUE TITLE
Create login view for company

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#116]
To be done after #115 and using the extended end-point of login (listing the companies associated with the user).

UI - Should be a 2 step login:
* First page where user enters `username` and `password` (Done in a previous issue)
* Second page where we list user's companies and the user selects a company to login -> **What is aimed for this issue**

**Comment by CarlosNZ** [comment]
Suggestion, though we should probably get Deb to design this page/process:

First login screen like this:
![Screen Shot 2020-11-26 at 12 06 47 PM](https://user-images.githubusercontent.com/5456533/100290304-e5876400-2fdf-11eb-8ccd-f6c59962e37d.png)
changes into this (without loading a new page) after username/password is authenticated:
![Screen Shot 2020-11-26 at 12 07 28 PM](https://user-images.githubusercontent.com/5456533/100290355-00f26f00-2fe0-11eb-9e29-7f34339cb59f.png)

**Comment by CarlosNZ** [comment]
Just putting this here for discussion.

I'll implement this using the new permissions PR and my password hashing branch as a basis.

From my understanding, here is a rough outline of the **current** login/re-load process (sorry about the shoddy formatting, I find draw.io kinda awkward to use):
![Login procedure-Current Process](https://user-images.githubusercontent.com/5456533/104393092-7d4d0b80-55a8-11eb-89a1-b0860ff654f9.png)

And this is what I **suggest**:
![Login procedure-Suggested Process](https://user-images.githubusercontent.com/5456533/104393661-de291380-55a9-11eb-8d92-899555554c89.png)

Original draw.io diagram available [here](https://drive.google.com/open?id=10x5MythfzfNGUGUeCOrnx9Cf9JiDlOtl&authuser=carl%40msupply.foundation&usp=drive_fs)

### Comments

- I'd like to minimize the current double-up between the `/login` and /userInfo` endpoints, they're currently almost doing exactly the same thing. I think the login endpoint should be limited to:
   - authenticating login
   - providing a list of available organisations
   - JWT with userId and orgId (if selected/available)
   - minimal user info (only needed for displaying name on "Select Organisation" form)
- the `userInfo` endpoint shouldn't return JWT -- we already have it at this point
- the `currentUser` will also have `orgId` and `orgName` fields
- would like to rename the `login` method in UserState to `onLogin` to avoid confusion. It doesn't actually log in, it's the procedure that occurs after successful log in, so `onLogin` seems more appropriate.

Anything else, or other suggestions?

**Comment by andreievg** [comment]
Oops sorry
![Screen Shot 2021-01-13 at 3 20 40 PM](https://user-images.githubusercontent.com/26194949/104398059-eb96cb80-55b2-11eb-8401-ace68a6f72d7.png)
