### ISSUE TITLE
Properly logging user off problems found during field trip (April) 

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#1162]
- [ ] Fix problem with user logout is keeping some cached data - for ResetPassword
- [ ] Same problem of not loading Application correctly (Some random error about Integer = "") when cache isn't properly cleaned

**Comment by CarlosNZ** [comment]
I'd really love it if someone could describe exact steps to replicate this. Cos every time I try and look at it I can't reproduce the error. 🙄

**Comment by nmadruga** [comment]
No.... I don't know what could be missing. But it definitely stops happening after we clean the cache....

**Comment by CarlosNZ** [comment]
Aha! https://www.apollographql.com/docs/react/caching/advanced-topics/#resetting-the-cache

I'll try and do this ASAP.

**Comment by CarlosNZ** [comment]
This is what I'm still slightly confuse about:

> Another option is to reload the page, which will have a similar effect.

(from above link)

When we logout we currently do `window.location.href = '/login'` which forces a page reload, so this should already be clearing the Apollo cache, and indeed that seems to be happening when I look at Apollo in the browser dev tools.

So I'm still not sure what conditions induce these errors. 🤔

**Comment by CarlosNZ** [comment]
Keeping issue open until we can confirm problem is sorted.

**Comment by andreievg** [comment]
can replicate when using latest docker image, after loading snapshot tried creating user registration in new tab:

result from `getApplicationSerial`:

{"errors":[{"message":"invalid input syntax for type integer: \"\"","locations":[{"line":2,"column":3}],"path":["application"]}],"data":{"application":null}}

from payload

{
    "operationName": "getApplicationSerial",
    "variables": {
        "id": 150
    },
    "query": "query getApplicationSerial($id: Int!) {\n  application(id: $id) {\n    serial\n    name\n    trigger\n    __typename\n  }\n}\n"
}

**Comment by andreievg** [comment]
can consistely replicate with what nicole described, have two incognito tabs, one for template builde r home and one just login page, refresh template builder home, and try create register user

wanted to get more log, so in docker container did `lsof -i tcp:5000` and `kill -9 {pid}`, then ran
```
yarn postgraphile \
   -c "postgres://postgres@localhost/tmf_app_manager" \
   --watch \
   -r graphile_user \
   --show-error-stack=json \
   --extended-errors hint,detail,errcode \
   -q '/postgraphile/graphql' \
   -i '/postgraphile/graphiql' | tee /var/log/application_manager/graphile.log &
 ```
 
 response is now
 ```
{"errors":[{"errcode":"22P02","extensions":{"exception":{"errcode":"22P02"}},"message":"invalid input syntax for type integer: \"\"","locations":[{"line":2,"column":3}],"path":["application"],"stack":["error: invalid input syntax for type integer: \"\"","    at Parser.parseErrorMessage (/usr/src/application-manager-server/node_modules/pg-protocol/dist/parser.js:278:15)","    at Parser.handlePacket (/usr/src/application-manager-server/node_modules/pg-protocol/dist/parser.js:126:29)","    at Parser.parse (/usr/src/application-manager-server/node_modules/pg-protocol/dist/parser.js:39:38)","    at Socket.<anonymous> (/usr/src/application-manager-server/node_modules/pg-protocol/dist/index.js:10:42)","    at Socket.emit (events.js:400:28)","    at addChunk (internal/streams/readable.js:293:12)","    at readableAddChunk (internal/streams/readable.js:267:9)","    at Socket.Readable.push (internal/streams/readable.js:206:10)","    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)"]}],"data":{"application":null}}
```

**Comment by andreievg** [comment]
i tried latest postgraphile, didn't make a difference, it does look like the error is originating from postgres (or the way postgraphile uses postgres), will try a build with later postgres version

**Comment by andreievg** [comment]
don't need to have the big snapshot loaded, this is apparent in core snapshot

**Comment by andreievg** [comment]
also this happens on any query, not just getApplicationSerial, and you don't need to go to template builder home, just any page by the looks of it, refresh in one tab and in another incognito tab try to create user registration.

I tried a new build with postgres 14, didn't help. I think i need to go deeper into graphile sql statements

**Comment by CarlosNZ** [comment]
> I tried a new build with postgres 14, didn't help. I think i need to go deeper into graphile sql statements

😬

**Comment by andreievg** [comment]
works with permissions turned off
