### ISSUE TITLE
Plugins: Checkbox - when Nothing is selected shouldn’t be reviewable

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#1197]
<img width="672" alt="Pessoa responsável é diferente do que a solicitante" src="https://user-images.githubusercontent.com/16461988/168039507-3cd3d95f-51dc-42aa-8306-89bfed568ef6.png">

**Comment by CarlosNZ** [comment]
No, we explicitly changed this a while ago -- a non-response is a valid response for a checkbox and should be treated as such.

However, we do need to allow questions to be non-reviewable (and non-answers reviewable) generally (as brought up in recent meeting) -- so I'll make a new issue for that.

**Comment by CarlosNZ** [comment]
New issue for general case: #1199
