### ISSUE TITLE
New question plugin free text Search to match entity in a table

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#120]
## Requirements (suggested)

- lookup table is a evaluator expression (i.e. the work of getting the options is done by evaluator, so can be API or database query)
- User types a free-text code, is presented with matching entities from lookup table
- lookup table can be mapped values (i.e type a code, get a name), or matching name directly (it's a setting)
- Allow multiple selections?
- parameter for "minimum characters" that need to be typed before results appear (default 3?)

**NOTE**: the only entities we have in the database currently that have unique-value -> name mapping is application serial, so probably want to use this for testing. Should we also add a "Code" field to organisation for this purpose?

### Suggested implementation: 

Probably use the "Search" component: https://react.semantic-ui.com/modules/search/

**Comment by CarlosNZ** [comment]
Just to clarify -- this should use the Semantic "Search" component to find and display results:
![Screen Shot 2021-05-17 at 12 46 50 PM](https://user-images.githubusercontent.com/5456533/118418821-20a45d80-b70e-11eb-9ab0-542741e7a19a.png)

https://react.semantic-ui.com/modules/search/

**Comment by CarlosNZ** [comment]
Done. Looks like it wasn't linked to a PR.
