### ISSUE TITLE
Evaluate template element parameters in UI

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-web-app#124]
We've currently implemented the expression evaluator for visibility condition, required, editable and Validation.

However, we still need to use it to evaluate the actual parameters for each template element. (eg. "label", "placeholder", etc.)

**Comment by CarlosNZ** [comment]
Also -- recommend doing #130 at the same time.

**Comment by CarlosNZ** [comment]
Regarding priority -- we will need this if we want to have dynamically created option lists for drop-downs etc.

**Comment by CarlosNZ** [comment]
Okay, having thought about this some more, I think I agree with you @andreievg that the plugin itself should evaluate any dynamic parameter fields. This is mainly because there are loads of possible parameters for plugins and for the majority it wouldn't make sense to have a dynamic value, and it'd be cumbersome to have to express all fields in that format unnecessarily.

Having said that, it does mean that different plugins can choose to interpret certain fields as dynamic or not independently. So one plugin might evaluate `label` as a dynamic query, whereas another one might not. (Of course, we should aim to be consistent as much as possible).

So, I would suggest that each plugin stores the names of the fields that should be evaluated dynamically in the `pluginConfig.json` file, and we have standardised boilerplate at the top of each plugin that handles the evaluation using a common method. Does that sound okay?

**Comment by CarlosNZ** [comment]
One further question that arises from the previous comment:

Assuming some of the parameter fields can be defined as "dynamic expressions", should it be set for the whole plugin type (in which case, defining it in `pluginConfig.json` seems appropriate), or per template_action (i.e. each Action instance can define arbitrary parameters as dynamic), in which case it'd need to defined with an additional field in `template_action`?

**Comment by nmadruga** [comment]
@CarlosNZ do you consider this is already done? Or anything remaining to be done regarding validation of parameters?

**Comment by CarlosNZ** [comment]
@nmadruga -- No, it's not done. We'll need to do it soon if we want to be able to have dynamic choice lists in Drop-downs (for example)

**Comment by CarlosNZ** [comment]
Okay, here is my detailed suggestion for how this should work:

- For each element plugin, the `pluginConfig.json` file gets an extra field called `dynamicParameters` where the parameters that should be supplied as dynamic expressions are defined.  
  - e.g. for infoText, the field might be just: `"dynamicParameters": [ "label" ]`  
  - for the dropdownChoice plugin, the field would probably be: `"dynamicParameters": [ "label", "options" ]`
- In ApplicationViewWrapper, there is a new `useState` hook: `[ evaluatedParameters, setEvaluatedParameters ]`
- In ApplicationViewWrapper, the dynamic parameter fields are extracted from the element parameters and evaluated on load, (using a similar async array of Promises used in `useGetResponsesAndElementState`), then set using `setEvaluatedParamers` when all Promises resolve.
- The `parameters` prop that is sent to the plugin element is constructed using the re-combination of (original, non-dynamic) parameters and the evaluated `evaluatedParameters` from above.
- There is a `useEffect` hook in ApplicationViewWrapper watching the `allResponses` object, so that dynamic parameters get re-evaluated whenever a response changes.

Note that only the plugins that are currently on display (current page) get their dynamic parameters re-evaluated.
- There would be a similar process in the SummaryViewWrapper, but it only needs to evaluate once on load, as there are no changes to respond to. This is very similar to the SummaryView re-validation on load, which I'm doing now.

**Comment by andreievg** [comment]
> for the dropdownChoice plugin, the field would probably be: "dynamicParameters": [ "label", "options" ]

What do we do for parameters that rely on lookup table (or GraphQL or API end point) based on value of another response in the form ? Would this be queried whenever any response is changed on the current page ? (maybe that's ok, or we can have a plugin implement evaluation manually for that use case, I can see the "options" in drop down being one of those use cases)

Ideally, we would add an optimisation to only evaluate those parameters if something they rely on changes (can make an issue for that for future).

> In ApplicationViewWrapper, the dynamic parameter fields are extracted from the element parameters and evaluated on load

I would assume this happens in the useEffect hook mentioned in later bullet point.

Lastly, if original evaluation of parameters is in progress (on load, not the consecutive ones), do we want to try and show the ApplicationView, or wait until it's done ?

**Comment by CarlosNZ** [comment]
> What do we do for parameters that rely on lookup table (or GraphQL or API end point) based on value of another response in the form ? Would this be queried whenever any response is changed on the current page ? (maybe that's ok, or we can have a plugin implement evaluation manually for that use case, I can see the "options" in drop down being one of those use cases)
> 

Yes, they would re-queried on changes, but:
1. Only fields that are on the current page are re-evaluated; and
2. This is not much different to what we already have happening for validation and isVisibility, etc.

> Ideally, we would add an optimisation to only evaluate those parameters if something they rely on changes (can make an issue for that for future).

But yes, an optimisation to prevent unnecessary re-fetches is something we could add later. Perhaps we can add a some memoisation in the evaluator? Either way, I think the optimisation should be done outside these components -- i.e. the evaluation call is made no matter what, the evaluator module (or a wrapper for it) decides (later) if it needs to actually perform the API/GraphQL query again.

> > In ApplicationViewWrapper, the dynamic parameter fields are extracted from the element parameters and evaluated on load
> 
> I would assume this happens in the useEffect hook mentioned in later bullet point.

The list of dynamic field names would be pulled in once from config on load, but the re-evaluation would be within the useEffect hook.

> Lastly, if original evaluation of parameters is in progress (on load, not the consecutive ones), do we want to try and show the ApplicationView, or wait until it's done ?

I guess we should show it, with maybe a "Loading" message on elements that are still fetching? (Most would be instantaneous, it's only API/DB calls that may take some time)

**Comment by andreievg** [comment]
ok, looks good to me.
