### ISSUE TITLE
Plugin -- move "general" functionality to ApplicationViewWrapper

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-web-app#126]
Move boilerplate, including update methods, validation methods, etc. to Wrapper component.

Also -- as suggested [here](https://github.com/openmsupply/application-manager-web-app/pull/125#pullrequestreview-533922233)

- Password hashing logic
- Maybe second entry validation on keystroke could be optional via parameter ?
- When field A shows message for validation of other fields, error will persist unless something is entered in filed A (I think this will be dealt with here: #126)

And maybe, if time:
- Multiple validations

**Comment by andreievg** [comment]
Proposal:

Plugin exposes a method `validate`, which is used by the wrapper.

Plugin ApplicationView **parameter change**:

`onUpdate(jsonValue)` <- is called on every keystroke etc..
`save(jsonValue)` <- is called when save needs to happen (i.e. onBlur)
`validationState` <- from validation method evaluation int the wrapper

Plugin **validate method**:

`Params`:
* jsonValue
* parameters <- from templateElememt
* evaluate() <- this method already has all of the object provided to it, i.e. `evaluate = (validationExpression) => { evaluateExpression(validationExpression, { objects: [thisResponse, ...allResponses], APIfetch: fetch }) }`

`Return`
* `{isValid, validationMessage, ..other things that plugin might need to pass from it's own validation method}` <- Passed through to plugin.


`Maybe second entry validation on keystroke could be optional via parameter ?` -> would need to store something in jsonValue to indicate second entry
