### ISSUE TITLE
useGetResponsesAndElementState hook -- should only return 2 objects, not 3

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-web-app#130]
Currently it returns:
- responsesByCode ([code]:[text])
- responsesFullByCode (same, but full response object rather than text)
- elementsState (evaluated states (isVisible etc) by code)

These last two can be combined together.

Recommend doing this issue at the same time as #126 since they'll be poking around in the same area.

**Comment by andreievg** [comment]
Hmm, I've also seen a bunch of times where we have to extract elementState of responses for a page.

Was wondering if userGetResponsesAndElementState can be a common place do any reductions needed further up? Or if that's a bad idea

**Comment by CarlosNZ** [comment]
> Was wondering if userGetResponsesAndElementState can be a common place do any reductions needed further up? Or if that's a bad idea

What do you mean? Isn't that what it's doing already?

**Comment by andreievg** [comment]
That paragraph also includes the paragraph above, `It makes more sense when you also include the comment above that one`

I was meaning to also reduce into pages an sections maybe, and return another result:

elementStateBySectionAndPage[section][page]

Weighing in a generic method do do that from elementState or for the hook to do a little extra

**Comment by CarlosNZ** [comment]
> Was wondering if userGetResponsesAndElementState can be a common place do any reductions needed further up? Or if that's a bad idea

That's a good idea -- we have done the page-number calculation in here and returned SectionIndex and PageIndex with this object so isolating per page is now a simple filter. Nicole will be pushing a PR for that soon, and then I'll quickly do this issue on the back of that -- it should be fairly simple now.
