### ISSUE TITLE
Display submission page after submit an application 

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#138]
**Updated description on 29/12 after creation of Epic#24**

## Scope
- Show submission message on Summary page upon successful submission
- After the application is submitted (and the trigger finished to run) go to the submission page after submission
- Show alert (modal?) if submission unsuccessful before re-directing to first invalid page (this part already done)
- Link to summary page and back to template list (e.g. Drug registrations) when the trigger has finished processing and the submission page is shown as it would for a completed application - the submission page should continue to be accessible.
- When submission page is accessed before the application is submitted, redirects to first invalid page. 

<img width="840" alt="Overview-of-Navigation- -URL-structure-Submission-page" src="https://user-images.githubusercontent.com/16461988/103321198-5d442500-4a9d-11eb-9f59-102f5ea5378d.png">

**Comment by nmadruga** [comment]
`application/serial/submit` new page, instead of modal.

DESIGN
![Screen Shot 2020-12-11 at 4 39 04 PM](https://user-images.githubusercontent.com/16461988/101858982-9b9da100-3bcf-11eb-9a73-70f9db9c296a.png)

**Comment by nmadruga** [comment]
Shouyld redirect the user if in draft status, probably some other cases too

**Comment by CarlosNZ** [comment]
Just checking -- did we agree that we should not show a modal, but show the custom end message at the top of the page, as well as remove the Submit and Edit buttons? I think that's we we got to after our last discussion, wasn't it?

Also -- this can probably become Issue 3 of the start/submit message mini-epic: https://github.com/openmsupply/application-manager-web-app/issues/182#issuecomment-747744264
