### ISSUE TITLE
Component consistency/Style discussion

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-web-app#139]
Need to have some kind of "style-guide" to establish standards for what Semantic-UI components correspond to what kind of elements (label, description, lists, headers, etc.)

### General rules
- Using the final elements such as Table, Button, Input, Header and Labels with global styles defined in one of the specific files for the element on the `semantic/src/site` folders: `elements`, `collections`, `models` and `views`.
- Or overall styles (not specific to one component) to be defined on one of the `semantic/src/site/globals` files.
- Check that we have overwritten the basic styles for H1, H2, Header and Label to be used as native Semantic already on the files `semantic/src/site/globals/site.variables`, `semantic/src/site/globals/site.overrides` and `semantic/src/site/elements/header.overrides`. Follow this example for more global layouts to be defined next.
- Colours we have a very basic list, and semantic has a small list of basic colours defined. We will try and map those so we can refer to color as `color="red"` in the semantic components on `semantic/src/site/globals/site.variables`.

### Detailed approach for classes vs. Index
- Regarding whether to use `<element_type>.overrides` or `site.overrides`, it's important to note that the "element" styles come _after_ the "site" ones, so you _must_ put them in the element files. If you try and redefine an element style in `site.overrides` it won't work, as the existing element definition will come after it in the output CSS.
- If you need to create _new_ custom classes (as opposed to overriding existing ones), try and stick to one of the following "rules":

  1. Try and make them small, and reusable, and give them a name that says clearly what it does. e.g. `red: {color: red}`, then we'd know that any time we wanted to make red text, we just need to add this class name to the element. Structural ones can be re-usable too:
     - e.g. `flex-row-centered-elements: {display: flex, flex-direction: row, justify-content: centered}` 
     Only add the minimal properties required to achieve what you want. It's better to use more than one "general" class name on an element (e.g. one for positioning, one for font-weight, say) than creating an overly specific class that is only used in one place.
   2. If a class _does_ need to be specifically tied to one particular element, see if you can define it by `id` (e.g. `#footer`) rather than a class name. And make the name really clear what it's going to be used for (e.g. `#footer-content`)

- Don't create "intersecting" class definitions if a "stand-alone" one doesn't already exist. There's no point making `.big-text .right` if `.big-text` and `.right` don't already exist on their own. You may as well just define `.big-text-right` as a single class, or -- even better -- define them both separately and just use them together on the same element.
- Keep definitions in the .overrides files and variables in the .variables file. It's not required for it to work, but it just makes organisation easier to manage. And if defining a variable intended to be mainly used in a component, put it in the `<element>.variables` file next to its usage in `<element>.overrides`. Note that variables can be defined _anywhere_ and they'll still work wherever they're used, so it's fine to use a variable in another component.

### Workflow
Our goal for the current Sprints (28~30) is to define all Global styles required (basic colours, font and style of elements), and work on existing Layout to make it more as in the designs. 
* Check all elements are using the proper fields (e.g. `h1` or `h2` for a title) on each page. 
* Remove all of the inline styles defined in each file (`// Styles - TODO: Move to LESS || Global class style (semantic)`)
* Replace existing css definitions (check what is in each `.less` file - BUT DON'T replace any code on `.less` please:
 Change styles by overwriting the `css` existing classes on one of the following:
    1. `semantic/src/site/global/site.variables` to re-define variables to be used for more than one element type
    2. `semantic/src/site/global/site.overrides` to create or overwrite css class to be used for more than one element type
    3. Specific changes to **<element_type>**  (e.g. Button) to overwrite `css` definitions of each `<element_type>.less` in one of the **<folder>**: `elements`, `collections`, `models` and `views`: 
      - `semantic/src/site/<folder>/<element_type>.variables` to re-define variables for an specific type
      - `semantic/src/site/<folder>/<element_type>.overrides` to create or overwrite css class for an specific type

Super-helpful explainer of precedence and specificity with CSS: https://css-tricks.com/specifics-on-css-specificity/

**Comment by CarlosNZ** [comment]
Yeah, seems good. I'd add a couple of other guidelines and bits of info. Some are largely just my personal opinion, so feel free to disagree ;)

- regarding whether to use `<element_type>.overrides` or `site.overrides`, it's important to note that the "element" styles come _after_ the "site" ones, so you _must_ put them in the element files. If you try and redefine an element style in `site.overrides` it won't work, as the existing element definition will come after it in the ouput CSS.
- If you need to create _new_ custom classes (as opposed to overriding existing ones), try and stick to one of the following "rules":
   - try and make them small, and re-useable, and give them a name that says clearly what it does. e.g. `red: {color: red}`, then we'd know that any time we wanted to make red text, we just need to add this class name to the element. Structural ones can be re-usable too:  
   e.g. `flex-row-centered-elements: {display: flex, flex-direction: row, justify-content: centered}` Only add the minimal properties required to achieve what you want. It's better to use more than one "general" class name on an element (e.g. one for positioning, one for font-weight, say) than creating an overly specific class that is only used in one place.
  - If a class _does_ need to be specifically tied to one particular element, see if you can define it by `id` (e.g. `#footer`) rather than a class name. And make the name really clear what it's going to be used for (e.g. `#footer-content`)
- Don't create child classes if a "stand-alone" one doesn't already exist. There's no point making `.big-text .right` if `.big-text` and `.right` don't already exist on their own. You may as well just define `.big-text-right` as a single class, or -- even better -- define them both separately and just use them together on the same element.
- Keep definitions in the .overrides files and variables in the .variables file. It's not required for it to work, but it just makes organisation easier to manage. And if defining a variable intended to be mainly used in a component, put it in the `<element>.variables` file next to its usage in `<element>.overrides`. Note that variables can be defined _anywhere_ and they'll still work wherever they're used, so it's fine to use a variable in another component.

**Comment by andreievg** [comment]
Just read through this, thumbs up, except I wasn't sure what this suggestes:
> Using the final elements such as Table (Grid), Button, Input, Header and Labels with global styles defined in the theme default and overall styles (not specific to one component) are defined on the site file. And overwriting the basic styles for H1, H2, Label, Input, etc to be used as native Semantic.

Meaning we don't play around with `default` theme, we are changing them in `site` ?

**Comment by CarlosNZ** [comment]
> Meaning we don't play around with `default` theme, we are changing them in `site` ?

Yes, we're not touching the "theme" files. I guess we could -- at some point down the road -- take all our changes in "site" and put them in their own theme (or overwrite default), but there's no need to think about that yet (other than it being possible).

**Comment by nmadruga** [comment]
> > Meaning we don't play around with `default` theme, we are changing them in `site` ?
> 
> Yes, we're not touching the "theme" files. I guess we could -- at some point down the road -- take all our changes in "site" and put them in their own theme (or overwrite default), but there's no need to think about that yet (other than it being possible).

Sure, I think this was written some time ago, so need to update now. I'll also add Carl's inputs to the description of this issue.

**Comment by nmadruga** [comment]
Have updated the description with additions from Carl and rephrasing a little the first block and last block. Hope it is easy to follow, and if anything extra needed just let me know (or update if that's easier) : )

**Comment by nmadruga** [comment]
@andreievg & @CarlosNZ Will be closing this issue now since there seems to be an agreement for all of us.

**Comment by CarlosNZ** [comment]
> @andreievg & @CarlosNZ Will be closing this issue now since there seems to be an agreement for all of us.

Where are we keeping the "final" guide? Wiki page?

**Comment by nmadruga** [comment]
It's linked on the top of the [Epic#10](78) for our future reference - don't think it needs to go to the wiki yet.
