### ISSUE TITLE
Build components for Basic user registration applications

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#14]
UI layout should be coming from designer next week (12/10/2020). Start with the most basic layout that display all elements/sections from what is fetched from GraphQL (saving to cache). On submit should trigger the action to save the new user.

**Comment by CarlosNZ** [comment]
Suggested question structure (update as required):

1. **First Name**
    - Type: _ShortText_
    - Required: True
2. **Last Name**
    - Type: _ShortText_
    - Required: True
3. **Username**
    - Type: _ShortText_
    - Required: True
    - Validation: Must be unique, Alphanumeric chars only, no spaces
4. **Email**
    - Type: _ShortText_ (If semantic-ui has its own built-in email validator, then maybe we make a new Type for email input?)
    - Required: True
    - Validation: Email REGEX check, must be unique in system
5. **Password**
    - Type: _Password_ (Basically same as short text, but with masked input chars)
    - Required: True
    - Validation: At least 8 chars, must contain at least one letter and one number (REGEX)
6. **Category of Organisation to join**
    - Type: _Checkbox_
    - Options: Manufacturer, Distributor, Importer
    - Required: False
7. **Select Manufacturer**
    - Type: _DropDown_ (or _autocomplete_?)
    - Options: Database call to list Manufacturers
    - Visibility_condition: Answer to Q6 = "Manufacturer"
    - Required: true
8. **Select Distributor**
    - Type: _DropDown_ (or _autocomplete_?)
    - Options: Database call to list Distributors
    - Visibitility_condition: Answer to Q6 = "Distributor"
    - Required: true
9. **Select Importer**
    - Type: _DropDown_ (or _autocomplete_?)
    - Options: Database call to list Importers
    - Visibitility_condition: Answer to Q6 = "Importer"
    - Required: true

Note: Questions 8-10 will have to also return a database link to be stored with the response (i.e. table and ID) so can be matched to organisation subsequently (we have allowed for this functionality in `evaluateExpression`'s GraphQL operator). Not sure if this would be a different plugin type or be allowed functionality in existing plugins.

**Comment by CarlosNZ** [comment]
Removed the Date of Birth/Date picker for now.
