### ISSUE TITLE
Unify types and reuse of evaluated responses object on SummaryView and ApplicationView 

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#143]
Reuse what was done in **hook** `useGetElementsAndResponsesQuery` (to return an object with one `elementState` type per element for the application and the evaluated responses in other objects `ResponseFull` and `ResponsesByCode`types) in a new **hook** `useGetSectionElementAndResponses` to the a very similar thing for a section.
The idea is to merge this two hooks one day if possible, but for now only doing very similar things in both and calling a unique helper to evaluate all elements that were queried by each hook.
This same hook would be used to list all **elements & responses** in a single page and in the summary, which would required changing the types currently received by `ApplicationViewWrapper` and SummaryViewWrapper`.

**Comment by CarlosNZ** [comment]
Yeah, definitely some functionality regression here compared with #127. The progress bar PR seems to be working fine, but in this one the on-page validation is broken. There's no error message popping up on invalid fields, and the "Next" button doesn't seem to move the page forward whether or not the fields are valid.
