### ISSUE TITLE
Make user info available in local state

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-web-app#145]
So it can be passed to the evaluator, or other parts of the app.

User info that should be available:
- First & Last name
- username
- email
- date of birth?
- permissions?
- Org name

Also, info about current application:
- serial no.

**Comment by andreievg** [comment]
Can these be deduced via DB (if user id is available) ? 

Also can extend useGetUserPermissions (and login endpoint) to set 'userInfo' which can be available through response from login and userPermission end points:
https://github.com/openmsupply/application-manager-web-app/blob/0da5d6491908ef9676537689e8be4319892d8ad1/src/utils/hooks/useGetUserPermissions.ts#L21-L22

Can add extra bits to userInfo when deemed necessary. It can be used similar to how userPermissions context key is used:

https://github.com/openmsupply/application-manager-web-app/blob/0da5d6491908ef9676537689e8be4319892d8ad1/src/components/Main/AppMenu.tsx#L13-L15

https://github.com/openmsupply/application-manager-web-app/blob/0da5d6491908ef9676537689e8be4319892d8ad1/src/components/Main/AppMenu.tsx#L34-L37
