### ISSUE TITLE
Summary Wrapper -- validation

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#158]
The validation should run on the plugins SummaryView and display correctly on the summary page - for application (for DRAFT application),

**Comment by CarlosNZ** [comment]
Here is my understanding of how the Summary page should handle validation etc. Please correct me before I get to far into this issue (and #48 which I may do at the same time).

When loading the Summary page, each question has an `isValid` value of either `true`, `false`, or `undefined`, which is loaded using ApolloQuery. We also create a local boolean called `isStrict`, which is initially set to `false`.

The SummaryViewWrapper for each question then **re-runs** validation.
- If result is `true`/`false`, write result to database if changed (shouldn't happen very often).
- If undefined, leave as is.

The SummaryViewWrapper passes this value to each SummaryView plugin, which displays error state for `false` and normal display for `true` or `undefined`. (Error state is an error icon, plus the ValidationMessage)

When the user clicks "Submit", we change the `isStrict` value to `true`. The SummaryView entities then re-render and any that are `undefined` (and required) now show in error state.

If all required questions pass strict validation, the form Submission proceeds, else an error message shows along with the updated error states.

The actual **re-calculation** of validity is only done during page load. The rest of the logic on this page just uses the result of that calculation.

Note that `isStrict` is a local value only, so will be reset if refreshing or navigating away from the page.

**Comment by andreievg** [comment]
Agree with all

> When the user clicks "Submit", we change the isStrict value to true. The SummaryView entities then re-render and any that are undefined (and required) now show in error state.

I think showing required but not filled in, should be responsibility of wrapper ?

**Comment by nmadruga** [comment]
> When the user clicks "Submit", we change the isStrict value to true. The SummaryView entities then re-render and any that are undefined (and required) now show in error state.

I think the idea to use `isStrict` as a local variable is still undecided. We might want to keep showing the fields with problems to the user after they enter the **strict mode**. So the alternative would be to send the validation to the server once the submit button is clicked, and then the other pages would show the invalid icon on `undefined` fields too.
