### ISSUE TITLE
Create review when Reviewer goes to the application review page

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#159]
Should wait for [Back-end#136](https://github.com/openmsupply/application-manager-server/issues/136) is done and use the same logged user before clicking on the application.

The reviewer now has an `review_assignment` associated to each question on the application. By entering the same application we would be loading ~~(on another issue)~~ any existing `review_response` done by this reviewer.

~~This issue is only to create the new hook to associate the reviewer with an application!~~ 
If the application already have a review for that reviewer then doesn't need to create.

**EDITED**: When loading the page, first check if needs to create a review, and then load the new/existing review with all questions, assignment and review_responses for that reviewer.

## Scope:
- Create computed columns:
  - In `review_response` have access to `template_element`
  - In `review` to have access to `stage` of `application`

### On ReviewOverview:
- **Hook 1**: Load application (to set things on cache)
  - We will need the application `id`, `stage_id` - change existing `LoadApplication` hook for that. 
- **Hook 2**: Load existing `review` and `review_assignment` for current user.
- Display one of the options:
  - if review does not exist, check if there are any assignments:
    - if yes, then show **start review**
    - if no, then 404
  - if review exists and status = 'Changes Require' or 'Review Pending' then show **continue review**
  - if review exists and status = 'Draft' or 'Submitted' then go to `/review/[appSerial]/[reviewId]`
  - if review exists and status is not one of the above, then something is up
- **Hook 3**: Create new review for reviewer, using the `review_assignment_id` and `reviewer_id`.

### On ReviewPageWrapper:
- **Hook 1**: Load application
- **Hook 4**: Get everything related to `review` based on the URL `review_id`.
    - Query to retrieve which `template_elements` questions are assigned to reviewer and existing `review_response`

Then the actual display of Review page to be done in #156.

**Comment by andreievg** [comment]
@nmadruga 

> Create computed columns:
> In review_response have access to template_element
> In review to have access to stage of application

I can see that stage on review would be useful ATM (for checking if review exists for current stage).

But not sure about `In review_response have access to template_element` (not saying you shouldn't add it, just don't think it would be used just now).

Btw check out generated application_id on review for examples

> Load application (to send the application, template_elements & application_responses on cache)

And also the evaluated bits `useGetResponsesAndElementState` (for visibility, and maybe to indicate 'required' vs optionals, in the future).

**Comment by andreievg** [comment]
@nmadruga, I think based on the following, we need to rethink it slightly. Do you want to have a go at outlining the hooks we need for both of those pages ? Otherwise I can do it.

https://github.com/openmsupply/application-manager-web-app/issues/200#issuecomment-741432161

**Comment by nmadruga** [comment]
I have updated this issue description. Hope it's all in there. I'm not sure yet about details such as how we would run a similar hook to what is done in the `useGetResponsesAndElementState`, but that's considered as part of the Hook 4, which to me shouldn't be included as part of this issue here. So it will be more focused on checking or creating the new review.

What do you think about it @andreievg ?

**Comment by andreievg** [comment]
Looks good to me, with a couple of questions and further thoughts:

> Hope it's all in there. I'm not sure yet about details such as how we would run a similar hook to what is done in the useGetResponsesAndElementState

When we create review_responses, do we want them created for all visible template_elements, or just for all template_elements (even if not visible), or for all visible that have been answered (i.e. if there is one that wasn't answered and it's not required, should reviewer be able to comment on it ?)

> Hook 2: Load existing review and review_assignment for current user.

That would be just be one query right ?

> if review exists and status = 'Changes Require' or 'Review Pending' then show continue review

In a new issue (I think) we can do the duplication of responses and change of status of review to draft for this one

Would  hook 4 be the same as hook 2 ? I mean should hook 2 also get review_responses ? (we would need previous responses when duplicating new responses, in the continue review bits)

> Hook 1: Load application
> Hook 4: Get everything related to review based on the URL review_id

Between these two I think we would need to `useGetResponsesAndElementState`

**Comment by CarlosNZ** [comment]
Just to chime in here -- Hook 2 should also include the `useTriggerProcessing` hook to wait until trigger is clear before loading review. It should work the same way it does in `useLoadApplication`, although it'll need to be updated to work for reviews (Issue made: #202)

**Comment by nmadruga** [comment]
Hi @andreievg, sorry I only saw this today:

> When we create review_responses, do we want them created for all visible template_elements, or just for all template_elements (even if not visible), or for all visible that have been answered (i.e. if there is one that wasn't answered and it's not required, should reviewer be able to comment on it ?)

This is actually a question for assignment. At this point, we already have all `review_question_assignment` to be used to create each `review_response`. I'll copy this comment to the Assignment Epic.

**Comment by nmadruga** [comment]
> [NM] Hook 2: Load existing review and review_assignment for current user.

>> [AE] That would be just be one query right ?

Yes

> [NM] if review exists and status = 'Changes Require' or 'Review Pending' then show continue review

>> [AE] In a new issue (I think) we can do the duplication of responses and change of status of review to draft for this one

Issue created #203 

> [AE] Would hook 4 be the same as hook 2 ? I mean should hook 2 also get review_responses ? (we would need previous responses when duplicating new responses, in the continue review bits)

>> [NM] Hook 1: Load application
>> [NM] Hook 4: Get everything related to review based on the URL review_id
> [AE] Between these two I think we would need to useGetResponsesAndElementState

The reason why there are 2 different hooks if mainly because **Hook 4** would be called by the second page, which is the one that actually show all responses and reviews, no need to load it before, and since the Hook 4 (to be worked as part of issue #156) will be more complicated it would just make Hook2 more complex which isn't needed.

**Comment by nmadruga** [comment]
> Just to chime in here -- Hook 2 should also include the useTriggerProcessing hook to wait until trigger is clear before loading review. It should work the same way it does in useLoadApplication, although it'll need to be updated to work for reviews (Issue made: #202)

Thanks! Creating another issue to deal with that: #204
