### ISSUE TITLE
Add start message and submission message for Templates

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#182]
**Updated description on 29/12 after creation of Epic#24**

## Scope
- Add two new TEXT fields to `template` table: `start_message`, `submission_message`
   - Submission message should have a default: "Thank you... etc.", but NOT the start message
- Write start and submission messages for existing templates (put in `insertData.js`)

**Comment by CarlosNZ** [comment]
Suggestion: If "start message" is null in database, the application goes straight to first page.
We can use this for "user registration", so new users don't have to go through the "Start application" page.

**Comment by CarlosNZ** [comment]
Here's my suggestion for breaking this into separate issues:

## Issue 1 (Effort 1?)
- Add two new TEXT fields to `template` table: `start_message`, `submission_message`
   - Submission message should have a default: "Thank you... etc.", but NOT the start message
- Write start and submission messages for existing templates (put in `insertData.js`)

## Issue 2 (Effort 2?)
- Front-end update to query these fields in the getTemplate query
- Display start message in ApplicationStart (ideally using evaluator, though that could wait until we create [stringSubstitution operator](https://github.com/openmsupply/application-manager-server/issues/158))
- If start_message is NULL, automatically create the application and go to the first page (we'd use this for userRegistration)

## Issue 3 (Effort 2-3?)
- Show submission message on Summary page upon successful submission (this is what we agreed we'd do, right? Not a new page?)
- Hide Submit button and Edit buttons after successful submission
- Show alert (modal?) if submission unsuccessful before re-directing to first invalid page (this part already done)

**Comment by nmadruga** [comment]
@CarlosNZ Thank you, I'm adding this new Epic now. I'll keep this one as an issue (issue 3 I think) and create a new one where I'll update with the list of issues as suggested in here. Will update this one shortly to point to it as well.
