### ISSUE TITLE
Build the User Registration application UI

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#19]
UI layout should be coming from designer next week (12/10/2020). Start with the most basic layout that display all elements/sections from what is fetched from GraphQL (saving to cache). On submit should trigger the action to save the new user.

**Comment by CarlosNZ** [comment]
Added suggested questions [here](https://github.com/openmsupply/application-manager-web-app/issues/14#issuecomment-703334055)
