### ISSUE TITLE
Validity check updates (Summary/Submit)

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#194]
Should first load all plugin specific validation same place that will be dealing with the visibility criteria.

Carl suggested to move the validation back to a field instead of part of the `parameters` field.

---
Updating with **agreed solution** (simplified, will comment back here if unexpected hurdles arise):

- Move "validation" and "validationMessage" back to their own columns in template_element table (and adjust templates accordingly)
- Write new method called `validateAll()` that re-runs validation on all responses and updates the `isValid` field (in database). Returns `true` (All valid) or `false` (At least one not valid)
   - has parameter "strict", so can be used for loose validation if necessary
   - takes array of responses as parameter, so can be used to validate whole application, or just one page if required
- Run `validateAll()` when trying to go to Summary page, don't allow if `false`
- Run `validateAll()` when trying to Submit -- don't allow if `false`
- DON'T run `validateAll` when individual responses change, this behaviour remains the same.

**Comment by CarlosNZ** [comment]
> Carl suggested to move the validation back to a field instead of part of the `parameters` field.

Yeah, I think validation and validationMessage can go back to being their own fields (instead of part of parameters), as that makes them more in line with "isVisible", "isEditable" and "isRequired" and can be evaluated along with them in `useGetResponsesAndElementStates`.
