### ISSUE TITLE
Bug -- Validation of Linear forms - problems with multi-pages/multi-sections

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-web-app#196]
These 2 bug only became apparent after creating [the new "ReviewTest" template](https://github.com/openmsupply/application-manager-web-app/pull/195) -- a **linear** template with multiple pages in multiple sections.

In order to reproduce, just start a new "Review Test form" application. You'll immediately see that the validation for Page 2 and Section 2 is showing in "error" even though we haven't advanced to those pages yet:

![Screen Shot 2020-12-07 at 5 14 33 PM](https://user-images.githubusercontent.com/5456533/101308837-b6120a80-38af-11eb-9c62-34845a5888ed.png)

After filling first page advance to Page 2. Notice the "Next" button is reading "Summary", even though there is another Section to go. Clicking it takes us to the Summary page, completely skipping Section 2.

Attn: @nmadruga

**Comment by nmadruga** [comment]
Having a look into this now.
