### ISSUE TITLE
Add action to set the first review_status_history to DRAFT after the review is created

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#204]
It should mirror the same process as in the application.

The action should be already in there, we need to check. Add to every template if not there (besides User Registration);

also create a documentation list of all DEFAULT actions that should be included in every template and think about how we set one as default (that cannot be deleted. And propose a solution.

**Comment by CarlosNZ** [comment]
Needs to happen after (or simultaneously with) #202

**Comment by nmadruga** [comment]
This issue also needs to add the action to set the first `review_status_history` as DRAFT after the review is created

**Comment by CarlosNZ** [comment]
The action exists, just need to add it to the templates -- will do now. Have added it to the [default list](https://github.com/openmsupply/application-manager-server/issues/184).
