### ISSUE TITLE
List applications with specific cells on each column

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#207]
[Updated on 12/01/2021]
## Scope
- List applications based on the `type` and `user-role` (filters)
- Don't do any other filtering based on the URL filters yet (to be done in #251)
- Don't do any ordering of columns yet (to be done in #209) or pagination of list (#210)
- The main focus of this issue is to display a different list of applications based on the current user (user-role) with different cells per columns (as shown in the Designs).
- Some columns that display for all user-roles:
  - Instead of `Drug name` column will be replaced with `Application name` regardless of template type
  - On the `actionable` column an icon would be displayed for applications that required attention (after a review/consolidation with "Changes requested" was submitted) 

#### Applicant
- Replace `date` with `Last active date` to display date when application was last edited
- Combine the application stage and status on the `stage` column. This change should be described on the `stage` filter values #225.
- Show a link to open the application labeled with one of the Applications possible actions* on the column `actionable` for applications with statuses.
- Should show a bin icon on last column (no title) for applications with status as **Draft**
- Show current progress on column `status`. Maybe should be implemented as part of #236.

\* Application actions:
`edit-draft`: **Draft** application status
`make-updates`: **Changes-required** application status
`renew`: **Expired** or **Withdrawn** application statuses
 _empty_ **Submitted** or **Re-submitted** application statuses

![Screen Shot 2020-12-11 at 3 12 34 PM](https://user-images.githubusercontent.com/16461988/101852809-55dadb80-3bc3-11eb-9dee-f58bfa864f8a.png)

#### Reviewer
- Similar to Applicant column `date`, but display date when application were **Assigned** or **Edited** by Reviewer.
![Screen Shot 2020-12-11 at 3 17 45 PM](https://user-images.githubusercontent.com/16461988/101853229-211b5400-3bc4-11eb-940b-909286305a78.png)
- Display columns `Company` and `Username` of Applicant.
- Display username of who have assigned reviewers in the `Consolidator` column. 
- Display the applicant stage on the `stage` column. This may be changed to also add the `status` as for Applicant?
- Similar to Applicant, should show a link to open the review labeled with one of the Reviewer possible actions*.

\* Reviewer actions: 
`start-review`: One review assigned to you without a review associated with application + stage
`continue-review`: One review assigned to you and **In progress** review status
`review-updates`: **Changes Required** after consolidator have asked for changes OR Applicant has Re-submitted. 
_empty_ (Review submitted)

### Consolidator
- Similar to Applicant column `date`, but display date when was **Received** (submitted by Applicant), **Reviewed** (by one of the Reviewers) or have been **Consolidated** to go back to Applicant or Reviewer. _Needs more thinking_
- Similar to Reviewer columns `Company` and `Username`
-  Show a link to open the review page (or plain text) label with one of the Consolidator possible actions*.

\* Consolidator actions: 
_Waiting to be assigned_: [Not a link] None review assigned associated with application + stage
`consolidate`: Some **Submitted** review submitted for application + stage
`review-updates`: **Re-submitted** application OR review after **Changes required** from consolidator
_empty_: **Submitted** consolidation

![Screen Shot 2020-12-11 at 3 18 02 PM](https://user-images.githubusercontent.com/16461988/101853246-24aedb00-3bc4-11eb-90dc-6f41e248f4e8.png)

### Questions & Answers
- Q: Assuming all applications are listed together for the Reviewer/Consolidator where would the template type be displayed?
  - We always should have a default for `type`, in case none is passed will be using the first one on the `templatePermissions` list of the current logged user.
- Q: How to display a specific property (e.g. company name) on the column for each template?
  - We have decided to **NOT** have dynamic columns per template type, we will be only adding dynamic fields to the `applicationName` with is a static column for all template types.
- We should probably add the `Outcome` column here as well. Should it show for all user-roles?

**Comment by nmadruga** [comment]
@CarlosNZ @andreievg I have updated this issue with what I consider as the scope for this issue. No details on the implementation yet, since there are a lot of translation from application fields to what will be displayed per user-role and for each column some specific rules. I'll add more information here when I have a better understanding of my approach.

For now please, have a look on the scope and Q&A topic to see if it's very clear, or if something might be missing. I tried to isolate what shouldn't be consider in this issue, as we have a solid list of applications that can be improved in the issues to come.

**Comment by CarlosNZ** [comment]
>     * Instead of `Drug name` column will be replaced with `Application name` regardless of template type

That reminds me -- need to make an issue to dynamically create the application name. We had a brief discussion about it last year.

**Comment by CarlosNZ** [comment]
>     * Should show a bin icon on last column (no title) for applications with status as **Draft**

Probably the bin is in the same cell as the "Edit" action? (doesn't need its own whole column)

**Comment by nmadruga** [comment]
Thank you for the input Carl! I'll work with that in mind: 
> Probably the bin is in the same cell as the "Edit" action? (doesn't need its own whole column)

Starting this issue now - considering what was discussed (and included in #225) for columns and headers.
