### ISSUE TITLE
Sort applications

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#209]

**Comment by nmadruga** [comment]
See related comment: https://github.com/openmsupply/application-manager-web-app/pull/265#discussion_r559304061

**Comment by CarlosNZ** [comment]
Can this be closed now?

**Comment by nmadruga** [comment]
No. Even though you already added the logic for columns to be sorted and UR to return the list sorted we still need to implement it on the UI

**Comment by CarlosNZ** [comment]
Duh, of course. Thx

**Comment by CarlosNZ** [comment]
Just want to clarify a couple of things before I get into this:

- Even though the query can handle sorting by multiple columns, the UI will only allow single-column sort. You click on one, it sorts by that, you click on another, it sorts by that instead. Is that correct?
- The actual sorting is done by the database and returned sorted, so the UI elements here are just for indication and only update the URL, right?
