### ISSUE TITLE
Bug: Clicking Next while still focused in Text input field doesn't validate

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-web-app#214]
Same for clicking "Review & Summary". If you click the buttons while still in an input box, you'll get the Invalid error.

This must be because the result of the input is not written to database until onLoseFocus. 

--- 

### Proposed solution (UPDATED from below comments and discussion):

- Create a new state value in ApplicationState Context Area called `inputElementsActivity` with the following shape, and a "set" action for each timestamp field:
```
{
  elementEnteredTimestamp: <Date> 
  elementLostFocusTimestamp: <Date> 
  elementsStateUpdatedTimestamp: <Date>
  areTimestampsInSequence: <boolean>
}
```
- ApplicationViewWrapper imports `setElementEnteredTimestamp` and `setElementLostFocusTimestamp` methods, and creates one new method `setIsActive()`, which simply runs `setElementEnteredTimestamp` if true, and `setElementLostFocusTimestamp` if false. The `setIsActive` method is passed to the plugin as a prop.
- Plugins have an `onFocus` event which calls `setIsActive()`
- The `setActive(false)` call can be made at the end of `onSave` (need to make sure async calls within onSave (such as `responseMutation`) are `await`ed).
- Add `setElementsStateUpdatedTimestamp` to `useGetResponsesAndElementState` and call it last in the `useEffect` responding to changes in `responsesByCode`
- Whenever one of these "set" actions runs in ApplicationState, the `areTimestampsInSequence` boolean is recalculated.
- On the Navigation (Prev/Next) buttons, Progress bar links, and the Review & Sumary button handlers, add a check to `areTimestampsInSequence` value -- if `false` don't proceed. Maybe add a `while (areTimestampsInSequence === false)` loop (with appropriate timeout) so operation can proceed once update is finished.

**Comment by nmadruga** [comment]
@CarlosNZ This looks good. My only concern is: if the element is in focus, when the user clicks the next button or the "Review & Submit" the focus on that element is always removed? That's why you though about doing that while at the end?

**Comment by CarlosNZ** [comment]
> My only concern is: if the element is in focus, when the user clicks the next button or the "Review & Submit" the focus on that element is always removed?

Clicking something else takes the focus away regardless. By definition, if you've clicked something, that's now the focus, right?

**Comment by andreievg** [comment]
> In the onSave method (in ApplicationViewWrapper), set this value back to false at the end of the method.

I am not sure this is enough. From my understanding, the issue is with delay between mutation and values being re-fetched and re-validated.

I think we need to consider the following 'things':

Latest 'onActive' time (when plugin was 'entered')
Latest 'onInactive' time (when plugin lost focuse)
Latest 'recalculation' of validity.

And we have to check the each on of the above is in order.

I am assuming in this case that 'recalculation of validity' happens with the latest response.

I was hoping that in our implementation of pageValidation, we would do current pageValidation right useGetResponsesAndElementState is done (as which stage we set a timestamp for it).

**Comment by CarlosNZ** [comment]
Okay, original posted updated based on discussion and comments.

**Comment by andreievg** [comment]
@CarlosNZ 

Looks good, but some further suggestions:

> ApplicationViewWrapper imports setElementEnteredTimestamp and setElementLostFocusTimestamp methods, and passes them down to plugin as props.

I was hoping we can abstract it from actual plugin. Plugin just needs to have a method to suggest 'i am active', and 'i am not active' (the later can perhaps be deduced from onSave event).

> Add setElementsStateUpdatedTimestamp to useGetResponsesAndElementState and call it last in the useEffect responding to changes in responsesByCode

Would prefer if we had a hook for this in ApplicationPageWrapper, useEffect that watches elementState

**Comment by CarlosNZ** [comment]
> I was hoping we can abstract it from actual plugin. Plugin just needs to have a method to suggest 'i am active', and 'i am not active' (the later can perhaps be deduced from onSave event).

Sure, so the plugin just runs `setIsActive(true)` which makes the Wrapper run `setElementEnteredTimestamp(<Date>)`? 

> Would prefer if we had a hook for this in ApplicationPageWrapper, useEffect that watches elementState

So a new hook? And we pass in `elementsState`?

**Comment by CarlosNZ** [comment]
So one issue is that if you go into a field and then exit it without actually changing anything, the `setElementsStateUpdatedTimestamp` won't run, as it only runs when `elementsState` changes.

I can put this at the end of `onSave` instead, and that looks like it *should* work, but we can't guarantee that `responsesByCode` will have been updated. What I think I'll need to do is have an additional check at the end of `onSave` to see if the new value matches the value in `responsesByCode` and run `setElementsStateUpdatedTimestamp` there if it hasn't changed. (If it has changed, it will run after elementsState changes).
