### ISSUE TITLE
Documenting List applications headers and functionality

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#225]
Some columns should be base and would show for all template - independent on the user role.
Should we have columns specific for template. e.g Drug registration: `drug name` and `company`, Company registration would have `company`, `user`.  OR we would have the same columns for all templates, and use the `Application name` to set specific information on each template. - For iteration 1 we should keep it simple and use the specific `application name` 

There will be differences on what are the headers and what is showing in each cell based on the user role. 
Discussed that url should continue to be general one that has different filters to display based on a application template or application category. Also we will be using the user role as one of the filters to display applications to make simpler on which columns and actions will be displayed based on the user role. 

[EDITED 11/01/2020]

## Filters:
- type (default: first from list of template-type in `templatePermissions` list)
- user-role (default: first role of template-type in `templatePermissions` list)
- category
- stage
- sort-by
- page
- per-page
- search
- date (default:"Today")
- outcome (default: "pending")

### User-role related filters
- last-active-date [Applicant, Reviewer, Consolidator] - dates per user last action
- deadline-date [Applicant]
- action* [Applicant, Reviewer, Consolidator] - different values
- consolidator [Reviewer]
- assigned [Consolidator]

\* The **action** filter should list applications in the same `status`, by showing the main action that the user can make in order to continue this application workflow. And the possible values are defined per `user-role`.
E.g: **Action** `view` to list all application which the user doesn't have any available action (already submitted).

### Combined filters
- For different filters are use in the same URL the query will be using **AND** logic between different filters.
E.g: `applications/type=CompRego&date=today`
- For the same filter with more than one value the query will be using **OR** logic between values in same filter.
E.g: `applications/type=CompRego&date=this-week,last-week`

## Workflow:
1. Parse the url query
2. Each query should correspond to a filter on the GraphQL query
   - The query might be different depending on the user role
3. Get back all the applications to be displayed
4. Update URL with any changes needed
5. Check user role to display columns and cells with all application retrieved.

## Up-to-date document
More details about each filter and URL structure for listing application in this [document](https://docs.google.com/document/d/1zjEcxgw48MIii2KDytf5g7qHJi3VPqq4OV9Dmxz5tNw/edit)

**Comment by CarlosNZ** [comment]
Add the link to the documentation here @nmadruga please

**Comment by CarlosNZ** [comment]
Additional queries that we mentioned at our last meeting:
- date start
- date end
- date (="Today")
- AND/OR logic (but simple)
- sort column
- outcome (default: "pending")
- ??

**Comment by nmadruga** [comment]
I have added all the current filters that we have been discussing in the document also in this issue description now. @CarlosNZ I think that what we have agreed for dates is to use the string `today`, `this-week` for periods or a single date in the format "DD-MM-YYYY". So all that is considered in the filter `date`.

Also what is the date that we are filtering these applications is still under discussion. Is it the **Last active** date - which would be different depending on the logged user - as per some UI designs? Or would it be the date when the application was submitted in the system.

**Comment by CarlosNZ** [comment]
> Also what is the date that we are filtering these applications is still under discussion. Is it the **Last active** date - which would be different depending on the logged user - as per some UI designs? Or would it be the date when the application was submitted in the system.

Right, I think they would each be separate filters. "last-active-date=", etc.
And the value for a date would be any of:
- A "word", eg. "today", "this-week", etc.
- a specific date string, e.g. "2020-01-11"
- a date range, e.g. "2020-01-01:2020-01-11" (syntax to be decided).

**Comment by nmadruga** [comment]
> Right, I think they would each be separate filters. "last-active-date=", etc.

I see, and what would be the `date` filter that you have commented before? Or we would only have `last-active-date` or `deadline-date` with this type of filter by date or no simple `date` key. Are we in the same page?

**Comment by nmadruga** [comment]
> And the value for a date would be any of:
> * A "word", eg. "today", "this-week", etc.
> * a specific date string, e.g. "2020-01-11"
> * a date range, e.g. "2020-01-01:2020-01-11" (syntax to be decided).

Fine by me. :)

**Comment by CarlosNZ** [comment]
> I see, and what would be the `date` filter that you have commented before? Or we would only have `last-active-date` or `deadline-date` with this type of filter by date or no simple `date` key. Are we in the same page?

Yeah, I guess there'd be no actual "date" filter, it'd always be `last-active-date` or `deadline-date` etc.

**Comment by nmadruga** [comment]
@andreievg @CarlosNZ  Please have another quick look on the document linked in the description and see if that's all good. Can you think about any other filters important for now? I know we have to think about `priority` at some point, but I just think for now it doesn't fit in our initial goal. Let me know what do you guys think, then I can transit this document in a wiki page with more details on each filter type.

**Comment by CarlosNZ** [comment]
Okay, it's looking pretty good. I've added a bunch of comments on there just now.

**Comment by andreievg** [comment]
It's looking good, with the comment that Carl made. 

I guess the only question is what the delimiters are (for sort direction, date range and multiple or filters/sorts).

We would need to extend applications with more computed columns by the sound of things (to expose more fields for filtered queries)

**Comment by CarlosNZ** [comment]
> I guess the only question is what the delimiters are (for sort direction, date range and multiple or filters/sorts).

As per the current comments/spec, would suggest:
- For splitting up date ranges, or tagging additional parameters: `:` (colon)    
   - e.g. `deadline-date=2021-01-01:2021-01-31`  
   - `sort-by=stage:asc`
- For multiple criteria: `,` (comma)
   - e.g. `type=CompRego&date=this-week,last-week`
-  Hyphen (`-`) for breaking up words (instead of camel case) or date delimiters
   - e.g. `last-added-date`
   - `2021-01-01`

**Comment by nmadruga** [comment]
Yes. that's it. All agreed I'll start to create the PR to move all the things from the document to a wiki page.

> We would need to extend applications with more computed columns by the sound of things (to expose more fields for filtered queries)

I'll try to think about it while I'm working on the documentation and will add ideas to the issue #251 when this is going to be implemented (and which by the way we haven't given an estimative yet). Any ideas? I would say that's probably a Effort 4.

**Comment by andreievg** [comment]
I am still not sure what exactly is being done in #251, without clearer scope it feels like effort 5+

**Comment by CarlosNZ** [comment]
> I am still not sure what exactly is being done in #251, without clearer scope it feels like effort 5+

Just quickly, how about breaking down #251 into the following issues:
- agree on URL syntax/standard (almost done)
- parse URL queries (using `useQuery`) into object of key-value pairs, and add any defaults (type, user-role)
- (regex?) parsers for converting keys and values into query conditions
- write GraphQL `getApplications` query using variables from above as conditions/filters

**Comment by nmadruga** [comment]
The PR with the documentation on wiki is ready for Review : )

> Just quickly, how about breaking down #251 into the following issues:

> agree on URL syntax/standard (almost done)
> parse URL queries (using useQuery) into object of key-value pairs, and add any defaults (type, user-role)
> (regex?) parsers for converting keys and values into query conditions
> write GraphQL getApplications query using variables from above as conditions/filters

To me it's already broken like that... 
#225 - agree on URL syntax/standard
#207 Add any defaults (type, user-role) and write GraphQL getApplications query just using `type`
#226 - parse URL queries (using useQuery) into object of key-value pairs
#251 - (regex?) parsers for converting keys and values into query conditions, include remaining filters in GraphQL query  from above as conditions/filters.

And next issues to improve the same query with search (#207), pagination (#210), sort (#209), dates specifics (#228), with a couple of more that we can review on the next estimative meeting.

**Comment by CarlosNZ** [comment]
> To me it's already broken like that...

Ah good, was just responding to Andrei's concern, but looks like it's already done :) Thx.

**Comment by nmadruga** [comment]
Yep, sorry. I was only replying to your comment to continue the discussion and adding which issues will be working with each part. The #251 issues would be dealing with most of the filtering and translation to a GraphQL query, but other issues would be doing part of the job beforehand, that's why it shouldn't be 5+.

**Comment by andreievg** [comment]
Ok, if it's just translating form query to GraphQL, then it's about a 4 imo
