### ISSUE TITLE
Display start page for draft application with existing start message

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#232]
## Scope:
- ~~Front-end update to query these fields in the getTemplate query~~
- ~~Display start message in ApplicationStart (ideally using evaluator, though that could wait until we create [stringSubstitution operator](https://github.com/openmsupply/application-manager-server/issues/158))~~ (Done basic display, just need to add evaluation)
- If start_message is NULL, automatically create the application and go to the first page (we'd use this for userRegistration)

**Comment by CarlosNZ** [comment]
Note: `stringSubstitution` is now in PR: https://github.com/openmsupply/application-manager-server/pull/164
