### ISSUE TITLE
Bug: Validation running on Submitted application (Summary view)

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#247]
After submitting an application and clicking on the button to see the Summary page:
![Screen Shot 2021-01-07 at 5 12 02 PM](https://user-images.githubusercontent.com/16461988/103850463-307eb600-510c-11eb-8054-c3a7d1e74344.png)

When it loads the summary page is running a validation and showing a "not unique username" problem:
<img width="740" alt="Screen Shot 2021-01-07 at 5 11 31 PM" src="https://user-images.githubusercontent.com/16461988/103850373-f31a2880-510b-11eb-8bc6-446466014fb0.png">

**Comment by CarlosNZ** [comment]
Ah yes, of course. Will just need to make sure the `revalidateAll` only runs if status = "DRAFT" or "CHANGES REQUIRED".

**Comment by CarlosNZ** [comment]
> Ah yes, of course. Will just need to make sure the `revalidateAll` only runs if status = "DRAFT" or "CHANGES REQUIRED".

This check is actually already there, so it's the same problem we're having on #235 -- the getStatus hook is returning status = "DRAFT", even when it's actually "COMPLETED" in database.
