### ISSUE TITLE
Document consolidation URL Flow

### ISSUE THREAD

**Issue by andreievg** [openmsupply/application-manager-web-app#269]
https://app.diagrams.net/#G1eELTV3Z_jJfJsuXJnZzn2l6I0jeGyG5a

![Consolidation URL Flow](https://user-images.githubusercontent.com/26194949/104871529-2d0ee880-59b0-11eb-91a1-8e86e31b969d.png)

Another diagram, to show how actions change consolidation:

https://app.diagrams.net/#G1E0ccefB_RmzV_fb9-e5Z1KunDjHJQDEq

![Consolidation Life Cycle](https://user-images.githubusercontent.com/26194949/104971278-27b6aa00-5a53-11eb-8e6c-33bca7bf9e8e.png)

**Comment by nmadruga** [comment]
Very good diagram. I agree that is very helpful for to have this during development.

I just have some questions which are regarding the Assignment statuses: When the user goes to the `/:applicationId/consolidation` page and no reviews have been done yet (but this user was the assigner) - if we consider that the consolidator may be the same as the assigner - do we display a page with sections and who is assigned to each section? 
I understand that this is part of the `Assigner` role, but I just wanted to understand if in this case the user sees this **Start page** even if the application-reviews have different status than the ones listed. 
In these cases what would be the "Consolidation status": 
- **waiting reviews** - when the consolidator is the same as the assigner
- **waiting assignment** - when there are no review-assigned, but the consolidator can assign

**Comment by andreievg** [comment]
@nmadruga good questions, let's discuss in our meeting and I update the issue

**Comment by andreievg** [comment]
While thinking of the [schema](https://github.com/openmsupply/application-manager-web-app/issues/281), I've realised there is a potential need to link reviews to consolidations (with one variant, using combined review schema for consolidation, this linkage can be know without even creating reviews or consolidations, so potentially it's possible to display consolidation page with no 'continue' button and no consolidation actually being created. 

I wont' add this to the diagram yet, as I think it's not required atm and it feels like it can be added in the future (with minor changes to existing logic).

I had a little think about responses (if they are created on front end):

It feels like the easiest solution is to change review status to `pending_consolidation` when new review is submitted. Which would bring consolidator to 'start page' with notification that new review has been submitted, and continue button will add responses for the new review. This will happen on refresh of-course.

**Comment by andreievg** [comment]
Diagram update for URL from (both review and consolidation in one):

https://app.diagrams.net/#G18YxT0F2ydq1P0zhQbZ4E8sdCoGm5X9ba

![Uploading Consolidation and Review URL 27-01 Flow (1).png…]()

**Comment by CarlosNZ** [comment]
At the end of the "self-assignment" row, the URL goes back to `../applicationId/review`. So that's the "home" page with "start" or "continue" option, right, as per higher up in the chart?

Should there be an arrow connecting this back, like so:

![Screen Shot 2021-01-28 at 11 20 46 AM](https://user-images.githubusercontent.com/5456533/106062201-54f20f00-615b-11eb-8e3b-5a4219ad0d1b.png)

**Comment by andreievg** [comment]
> At the end of the "self-assignment" row, the URL goes back to ../applicationId/review. So that's the "home" page with "start" or "continue" option, right, as per higher up in the chart?

Yeah that was the idea. I thought that it would be easier (implementation wise) to just refresh the page again. 

> Should there be an arrow connecting this back, like so:

Would it be ok to wait and see how the logic looks on the review page and see which way is easier ?

We could also do assign and start, all in one go, but I thought maybe we want that differentiation

**Comment by CarlosNZ** [comment]
> Would it be ok to wait and see how the logic looks on the review page and see which way is easier ?

Yeah, although by ending at `.../applicationId/review` you're kind of implying that it's now the same page as above.

> We could also do assign and start, all in one go, but I thought maybe we want that differentiation
 
Yeah, I'm thinking that it should be separate steps, so that after it's been assigned (self or other), it's an identical process from that point forward.

**Comment by andreievg** [comment]
And here is the lifecycle diagram: 

https://app.diagrams.net/#G1VIyFc7NjAEShXOQxgJoOvKgKrxbtsY0q

![Review Life Cycle 28-01-21](https://user-images.githubusercontent.com/26194949/106069400-51fd1b80-6167-11eb-8c0b-26eb11a2db3b.png)

**Comment by andreievg** [comment]
> Yeah, although by ending at .../applicationId/review you're kind of implying that it's now the same page as above.

@CarlosNZ I've updated: https://github.com/openmsupply/application-manager-web-app/issues/269#issuecomment-768610962

With this line ->

![Screen Shot 2021-01-28 at 1 00 21 PM](https://user-images.githubusercontent.com/26194949/106070204-ddc37780-6168-11eb-9fb4-8a9a14653f70.png)


Does that make more sense ?

**Comment by CarlosNZ** [comment]
> Does that make more sense ?

Yeah, makes sense. 👍
