### ISSUE TITLE
Element plugin: Checkboxes

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-web-app#270]
## Requirements:

- Can specify one or many checkboxes in one element. User can select as many as needed.
- Each checkbox can have a default selection state (checked/unchecked)
- A label for each checkbox
- Checkbox can also be a toggle switch or a slider switch (very simple variants with SemanticUI)
- ~~Needs a SummaryView (so it can show the multiple values -- default SummaryView won't do)~~

#### Input parameters:

- **label**: `string`
- **description**: `string`
- **checkboxes**: `array[string | object]` -- array of labels for checkboxes
   - if a string array, it'll just be a group of unchecked checkboxes. However, more specific details can be provided by providing objects instead, with the following parameters:  
   ```
   {
    label: <string> - Text to display next to checkbox (Can be empty string but not omitted)
    text: <string> - value to store in Resonse "text" field and shown in Summary View. Will be same as label if omitted.
    key: <string> - unique code used as index for Response object (for searching using subsequent evaluator expressions)
    selected: true/false (initial state)
   }
  ``` 
- **type**: `checkbox | toggle | slider` -- (default: `checkbox`). Changes the UI display to a toggle switch or a slider switch.
- **layout**: `inline | block` -- (default: `block`) If "inline", multiple checkboxes are laid out horizontally (space depending) [NOTE: Only bother with this if its a simple Semantic option]

#### Output (Response) object (JSONValue):

```
{
  text: <string> -- comma separated list of all selected checkbox "text" values -- for display in Summary view
  values: {
    'key1' : { text: <text value>, isSelected: true/false }
    'key2' : { text: <text value>, isSelected: true/false }
     ...
    }
}
```

#### Limitations of this suggested solution:

- It's straightforward to make a list of string array options from a dynamic evaluator query, but it would be tricky to build an object array. Which means dynamic queries can really only be used for the "simple" version (and can't have default selections, etc.)
- the _order_ of the original options list wouldn't be preserved in the response object. If this was important, you'd have to make sure you provided alphabetically ordered keys.

--- 

### Considerations (updated above based on comment discussion below)

This is a bit trickier than the previous plugins as the main reponse value will be more than just a `text` field. So I think it's worth doing soon as a basis for other "multi-value" plugins.

I suggest the main response object (`jsonValue` in wrapper should (in addition to the existing `isValid` field) should be a `value` field with the following shape:
Object with each property being the index of the checkbox item. Then each index field contains:
 ```
{
 text: <label of the checkbox> (or conditional "value" based on selection -- see below)
 selected: true/false
}
```
Why an object with index fields rather than an array? Main reason is the `objectProperties` operator currently can't drill down into arrays. We could update it to do so if that's a better option?

**Suggested input parameters:**
- **label**: `string`
- **description**: `string`
- **checkboxes**: `array[string | object] | ` -- array of labels for the checkboxes
   - if a string array, it'll just be a group of unchecked checkboxes. However, more specific details can be provided by providing objects instead, with the following parameters:  
   ```
   {
    label: <string>
    selected: true/false (initial state)
    trueValue: (optional -- a text value to store if the checkbox is checked)
    falseValue: (optional -- a text value to store if the checkbox is unchecked)
   }
  ``` 

- **type**: `checkbox | toggle | slider` -- (default: `checkbox`). Changes the UI display to a toggle switch or a slider switch.
- **layout**: `inline | block` -- (default: `block`) If "inline", multiple checkboxes are laid out horizontally (space depending)

**Comment by andreievg** [comment]
@CarlosNZ look pretty good, some minor suggestion tweaks

 > layout: inline | block -- (default: block) If "inline", multiple checkboxes are laid out horizontally (space depending)
 
 I can see dynamic styling being a bit tricky, perhaps not, plus inline and block don't sound very much like flex (maybe Semantic UI uses it's own types for alignment) ? Anyways, was wondering if this property is worth implementing at this stage. (thinking 'not' at the current stage)

> Object with each property being the index of the checkbox item. Then each index field contains:

Another option is to use a key (property) defined (unique) in the config for each checkbox. I kind of like that idea.

> Needs a SummaryView (so it can show the multiple values -- default SummaryView won't do)

Technically, default text summary view might work, if text value (auxiliary return) is a list of 'true' text: field defined in the configurations, i.e. 

```JS
configurations = [{
  label: 'First Checkbox',
  textValue: 'FirstCheckBox',
  // this one becomes key ?
  code: 'fcb',
  selected: false
},{
  label: 'Second Checkbox',
  textValue: 'SecondCheckBox',
  // this one becomes key ?
  code: 'scb',
  selected: false
}]
// say they are both checked
jsonValue = {
   text: 'FirstCheckBox, SecondCheckBox',
   values: {
   'fcb': { value: true },
   'scb': { value: true },
}

}
```

I dont' immediately see a use case for `trueValue` and `falseValue` btw. And not sure about the use case for: 
> text: <label of the checkbox> (or conditional "value" based on selection -- see below)

**Comment by CarlosNZ** [comment]
> > layout: inline | block -- (default: block) If "inline", multiple checkboxes are laid out horizontally (space depending)
> 
> I can see dynamic styling being a bit tricky, perhaps not, plus inline and block don't sound very much like flex (maybe Semantic UI uses it's own types for alignment) ? Anyways, was wondering if this property is worth implementing at this stage. (thinking 'not' at the current stage)

I just thought it might be simple, since several of the Semantic components have `inline` options built in. But yeah, not worth it unless it comes pretty much baked in.

> > Object with each property being the index of the checkbox item. Then each index field contains:
> 
> Another option is to use a key (property) defined (unique) in the config for each checkbox. I kind of like that idea.

Yeah, good idea -- let's go with that. :)

> > Needs a SummaryView (so it can show the multiple values -- default SummaryView won't do)
> 
> Technically, default text summary view might work, if text value (auxiliary return) is a list of 'true' text: field defined in the configurations, i.e.

Sure, so the "text" field can just be a comma-seperated list of the selected labels.

> I dont' immediately see a use case for `trueValue` and `falseValue` btw. And not sure about the use case for:
> 
> > text:  (or conditional "value" based on selection -- see below

I did have a use case in mind, but it's pretty obscure and can probably be achieved using evaluator expressions -- so let's leave it for now.

Thanks for the suggestions, will update original post.

**Comment by CarlosNZ** [comment]
> ```js
> configurations = [{
>   label: 'First Checkbox',
>   textValue: 'FirstCheckBox',
>   // this one becomes key ?
>   code: 'fcb',
>   selected: false
> ```

It's not often you'd want different `label` and `textValue`, except in cases where, say, an evaluator expression might want a different output than the "label" or the "Summary view". I'd suggest (as input parameters) the text value defaults to the same as label unless specified.

So, to clarify:
- `label` : what's shown next to the checkbox in the application
- `textValue` : what's is saved in the Response and shown in Summary View (same as `label` if omitted)

I can see a use case where we might leave `label` blank -- like for a single toggle switch -- in which case `textValue` would still provide something to save with the response and Summary view.
