### ISSUE TITLE
Update ReviewPage with Consolidator showing reviewer and consolidation comments

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#275]
Show ReviewPage with previous reviewers comments and the **Review** button (or another label for Consolidators?) after the consolidation was created and issue #388 is done. 
If no consolidation should redirect to start page as described in #269.

Consolidator Schema: #281

First needs to outline what is the differences in UI (and query) between lvl 1 review and consolidation review page.

UI Design

Reviewer
![Screen Shot 2021-01-29 at 12 19 15 PM](https://user-images.githubusercontent.com/16461988/106210836-7969ec00-622c-11eb-8e90-9accd94382bb.png)
![Screen Shot 2021-01-29 at 12 19 30 PM](https://user-images.githubusercontent.com/16461988/106210842-7c64dc80-622c-11eb-8e09-2985e2cd7e2c.png)

Consolidator
![Screen Shot 2021-01-29 at 12 19 00 PM](https://user-images.githubusercontent.com/16461988/106210845-7ec73680-622c-11eb-83e3-0ef17f651e3b.png)
<img width="616" alt="Screen Shot 2021-05-06 at 8 37 47 PM" src="https://user-images.githubusercontent.com/16461988/117268238-2cd92100-aeab-11eb-984e-d0496a1c7815.png">

**Comment by andreievg** [comment]
Thought to clarify the new shape of structure for this:

editable: status = 'Draft'.

if thisReviewLatestResponse.reviewResponseLink, then it's consolidation

latestOriginalReview response to be used in consolidation to render review response being consolidated (not editable for consolidation regardless of status)

i think `ReviewResponseElement` needs to take two reviewResponses as parameter:
for review it would be just thisReviewLatestResponse (for both, and render edit icon when thisReviewLatestResponse.decision exists)
for consolidation it would be latestOriginalReviewResponse and thisReviewLatestResponse (and if it's consolidation only render the 'Review' when thisReviewLatestResponse.decision does not exist)

I think we need another issue to render section progress (in home and in review page), logic for this would need to be decided from the new reviewProgress mentioned in https://github.com/openmsupply/application-manager-web-app/pull/631
