### ISSUE TITLE
Schema changes - considering 2 options

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#281]

**Comment by andreievg** [comment]
### Consolidation option:

https://app.diagrams.net/#G17f1MmmWjW4msfESgiMlVZwmTZpVFtf3V
![Consolidation 20-01-21](https://user-images.githubusercontent.com/26194949/105126124-ef8e9480-5b42-11eb-81b2-48578e9e8194.png)

### Review option

https://app.diagrams.net/#G1O54sBWzBWTjT616SBivN24x2079osPAF
![Review as Consolidation 20-01-21](https://user-images.githubusercontent.com/26194949/105126128-f3bab200-5b42-11eb-8b7d-5e12db03a84b.png)

There is a lot of duplication in the consolidation schema. We can combine the two as per review option, but need to be aware and super specific about documenting which fields/tables are used where. 

I like the assignment schema on review to be used for consolidation too (as per Review option), can pre assign reviews/consolidations to consolidations (without creating the consolidation review).

Kind leaning towards review option now. Perhaps another discussion on Thursday ?

**Comment by andreievg** [comment]
Latest schema:
https://app.diagrams.net/#G1Lh-Qh3WvjjtDy_xy_pOwuEeedrdjISJD
![Review as Consolidation 27-01-21](https://user-images.githubusercontent.com/26194949/105941130-9a61fe00-60c1-11eb-94f1-ee41e078cd2d.png)

**Comment by andreievg** [comment]
One more update (same doc as last comment), added timestamp to review_assignment
![Review as Consolidation 27-01-21 (1)](https://user-images.githubusercontent.com/26194949/106059685-ee1f2680-6157-11eb-9efc-5dd845f52db0.png)

**Comment by CarlosNZ** [comment]
> added timestamp to review_assignment

Is the timestamp for time created and only added once, or is it updated based on the actual assignment time?

**Comment by andreievg** [comment]
> Is the timestamp for time created and only added once, or is it updated based on the actual assignment time?

Created, just to know for current reviewer and current application what is the latest review_assignment record

**Comment by CarlosNZ** [comment]
> Created, just to know for current reviewer and current application what is the latest review_assignment record

Okay, but shouldn't there only ever be 1 record for a given reviewer/application/stage/level combination?
