### ISSUE TITLE
Diagram for Review status changes

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#282]
Make similar Diagram as in #269 for the Review creation and status update workflow

**Comment by andreievg** [comment]
The review URL flow is very similar to consolidation one:

![Consolidation and Review URL Flow](https://user-images.githubusercontent.com/26194949/105423544-96da0b80-5caa-11eb-97b9-c24f4ba2c1f8.png)

And the life cycle of review:

![Review Life Cycle](https://user-images.githubusercontent.com/26194949/105423572-a8231800-5caa-11eb-814e-163e2d892daf.png)

**Comment by andreievg** [comment]
Please refer to updates in this issue (both the lifecycle and the URL flow is combined for consolidation review and normal review): https://github.com/openmsupply/application-manager-web-app/issues/269
