### ISSUE TITLE
Logic to discard application (in Draft) when Applicant clicks the bin icon on the list

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#285]

**Comment by CarlosNZ** [comment]
Question: Does the logic to *display* the bin icon already take into account whether the user is allowed to delete it? If so, then I assume this issue would simply delete the database entries, given that if they can see the icon, they're allowed to delete it.

**Comment by nmadruga** [comment]
For now it should only set field `active` to false. And we need a filter for availability of application - so user can see removed applications.

**Comment by CarlosNZ** [comment]
> For now it should only set field `active` to false.

And set "status" to "WITHDRAWN"?
