### ISSUE TITLE
Schema changes (implementation)

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#291]
Changes to consider Consolidator as another review as per #281.

[UPDATED on 03/02/2021]
The fields on `review` and `review_assignment` previously named `can_make_overall_decision` to be replaced with `is_last_level` as BOOLEAN
On another meeting about `template_permission` the team agreed that the table shouldn't have the field `template_section_id` and we would like to add the `stage` (which is the stage number) in the table.

**Comment by CarlosNZ** [comment]
I have some thoughts about the URL structure in light of recent discussions.

Basically, there's three considerations that have come up that suggest some re-thinking of the URLs for reviews:

1. It’s not a great idea to have the database ID in the URL (the more I read about it, it seems not cool)
2. Reviews and Consolidations are now the same kind of entity in the system
3. Review levels (and their names) should be defined by a template (so can’t assume it’s “Consolidate”) (see [this comment](https://github.com/openmsupply/application-manager-server/issues/188#issuecomment-767868613))

## Proposed solution.

Say we have a template with the following review structure:

**Stage 1**: Screening
- Review Level 1: “Initial approval”

**Stage 2**: Assessment
- Review Level 1: “Review” (split into two sections)
- Review Level 2: “Consolidation”

**Stage 3**: Final Decision
- Review Level 1: "Approval"

The URL structure would be as follows:

`/application/[serial]/review` - review home page, same as current

`/application/[serial]/review/[stage]/[review-name (or level?)]/[number]`  - where `number` is an incrementing value for reviews of this stage/level, starting at 1

So the all the reviews for an application of this template (serial: 12345) would be:

- `/application/12345/review` - home page
- `/application/12345/review/screening/initial-approval/1`
- `/application/12345/review/assessment/review/1`
 - `/application/12345/review/assessment/review/2`
- `/application/12345/review/assessment/consolidation/1`
- `/application/12345/review/final-decision/approval/1`

Regarding “number”, we’d probably just generate it on review creation and store it in an additional field on the review table.

Regarding having `review` in the URL twice if the review level is just called “review”, we could always just drop the first “review” if it’s still clear enough, so:

- `/application/12345/screening/initial-approval/1`
- `/application/12345/assessment/review/1`
 - `/application/12345/assessment/review/2`
- `/application/12345/assessment/consolidation/1`
- `/application/12345/final-decision/approval/1`

(I think I prefer this one)

Thoughts?

**Comment by nmadruga** [comment]
It's a good idea Carl. I have the same concern about using `id` in the URL. That's a problem. 
Also think that this URL seems easier to understand and see what is the current step of the review. Although it looks good to drop the first review in the URL, I don't see what would be the start page in this case... Is it: `/application/[serial]/[stage]/[review-name (or level?)]/` so it will render with information that the user can see on that level of review? For example: `/application/12345/assessment/review` and Reviewer lvl 1 assigned to one section, display other sections as `Assigned to others` or if Consolidator... it would redirect to `/application/12345/assessment/consolidation` that is the start page of consolidation?

**Comment by andreievg** [comment]
As per https://github.com/openmsupply/application-manager-server/issues/189#issuecomment-768002635 `URL` section, for now agreed to keep existing way.

I really dont' think that URLs will be looked at or edited by users btw. And I haven't been convinced that showing IDs is less secure

**Comment by CarlosNZ** [comment]
> As per [openmsupply/application-manager-server#189 (comment)](https://github.com/openmsupply/application-manager-server/issues/189#issuecomment-768002635) `URL` section, for now agreed to keep existing way.

Existing way, but with no specific `/consolidate` path -- it'll all come in under `/review`.

**Comment by andreievg** [comment]
> Existing way, but with no specific /consolidate path -- it'll all come in under /review.

Oops yeah sorry
