### ISSUE TITLE
File Upload -- design spec

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-web-app#301]
First part of [Epic #41](#430)

## Schema

The "file" table should have the following fields:

- id (serial) (Primary key)
- unique_id (recommend https://www.npmjs.com/package/nanoid for generating)
- user_id
- application_id
- application_response_id
- original_filename
- file_path (on server)
- thumbnail_path (on server)
- mimetype
- submitted (boolean, default `false` -- set to `true` when application is submitted)
- timestamp (upload time)

### `/upload`

`POST` request with file(s) in the request `body` form-data:  
`key: "file" value: <File(s)>`

Additional (optional) fields:
- `user_id`
- `application_id`
- `application_response_id`

Note: optional fields can be supplied _either_ as additional `key/value `pairs in the request `body` _or_ as `query parameters`  
e.g. `/upload?user=2&application_id=3`

^ The above is already implemented. Need to add:
- create random uid (using https://www.npmjs.com/package/nanoid)
- generate thumbnail (if possible from file type) - find a suitable library that can convert image types AND Pdfs. For other files, reference a generic thumbnail for other common types (audio, video, etc.)
- return object:  
```
{ 
 success: true/false,
 files: [ { filename: <original_filename>, 
             fileUrl: "/file?id=XXXXX",
             thumbnailUrl:"/file?uid=XXXXX",
             mimetype: (from DB) }...]
 }
```

Note: for our system, we really only need to return the file uid. However, if we want to make the plugin able to work with alternative file servers at some point, URLs to both the main file and the thumbnail might be useful

- file store: saved as "<original_filename>_UID.<original_ext>" (Folder structure TBD), thumbnail saved as "<original_filename>_UID_thumb.<original_ext>"

### `/file`

Endpoint for retrieving files.

- `/file?uid=XXX` (where XXX is the random-string unique id of the file in the database)
- `/file?uid=XXX&thumbnail=true` (for associated thumbnail)

Server retrieves file based on unique id and serves it.

### Authentication

To be discussed and implemented later. For now, a hard-to-guess unique id should make files inaccessible.

## Front-end Form element plug-in

UI needs a wireframe (do we get Deb to do this?)

- Form element launches an file selection dialog on click.
- Shows loading spinner while file is uploading
- shows thumbnail once file is uploaded
- If multiple files allowed, there's a "Add another" button
- Ability to "delete" files that have been uploaded (before submission) *
- Clicking on uploaded file icon/thumbnail launches file in new browser tab (for MVP, can do something fancier later)
- Summary view will just have the thumbnail links part of the above
- Advanced feature (for later): each file can have a user-supplied "text" field (i.e. "caption"), useful when providing multiple image files and want to distinguish them

* Note on deletion: files are not actually deleted from server. We just run a periodic "clean-up" function that auto-deletes files older than a certain date with their "submitted" field set to `false`. (To do later)

### Plugin parameters

- `label`
- `description` (these two as per normal)
- `fileCountLimit` (number, default `1` -- specifies the maximum number of files user can upload for this question)
- `fileExtensions` (Array of strings, e.g. `["pdf", "jpg", "png"]` -- if not provided, there are no restrictions
- `fileSizeLimit`: (number, specifying the maximum file size in KB)

### Response object format

`{`
  `text`: comma-separated list of (original) filenames (all element types need a "text" field)
  `files`: **array** of: 
```
  { 
    filename: <string>
    fileUrl: "/file?uid=XXXX" (need to include host?)
    thumbnailUrl: "/file?uid=XXX&thumbnail=true"
    mimetype: <string>
  }
```
`}`

**Comment by CarlosNZ** [comment]
Planning to break this into issues with more details and specs

**Comment by nmadruga** [comment]
Just one idea here from a website that O was using to add some docs uploaded (using mobile web site), could be used for reference...

Before uploading file
![Screenshot_20210203-135655.png](https://user-images.githubusercontent.com/16461988/110858854-767c1400-831f-11eb-9874-7144886d943d.png)

File selection (is this native to each browser?)
![Screenshot_20210203-135701.png](https://user-images.githubusercontent.com/16461988/110859002-a7f4df80-831f-11eb-946c-d07ede94a230.png)

After file is uploaded
![Screenshot_20210203-135642.png](https://user-images.githubusercontent.com/16461988/110859026-ae835700-831f-11eb-8a54-17a16ab5217b.png)

**Comment by andreievg** [comment]
@CarlosNZ looks great, a few suggestions:

> multipleFiles (boolean, default false -- specifies if user can upload multiple files for this question)

file limit ?

> fileExts

fileExtension

I feel like the UUID field might not be needed on the table. (server generates UUID and embeds it in the filename), but I guess it's ok to have it.

### Thumbnails

Default thumbnails for commons types ? (if server fails to generate a thumbnail, just uses that one ?)

**Comment by andreievg** [comment]
@nmadruga, i've copied the images to https://github.com/openmsupply/application-manager-web-app/issues/431#issuecomment-797084237, might be a better place for them there (feel free to remove them from here, or keep here, up to you)

**Comment by CarlosNZ** [comment]
> Just one idea here from a website that O was using to add some docs uploaded

Cool, good UI suggestions.

> File selection (is this native to each browser?)

Yeah, for now we would just pop a native browser/OS file selection dialog when clicking the "upload" button.

**Comment by CarlosNZ** [comment]
> > multipleFiles (boolean, default false -- specifies if user can upload multiple files for this question)
> 
> file limit ?

Do you mean specify a number rather than just a boolean? (with default =1)

**Comment by andreievg** [comment]
> Do you mean specify a number rather than just a boolean? (with default =1)

yep

**Comment by CarlosNZ** [comment]
> I feel like the UUID field might not be needed on the table. (server generates UUID and embeds it in the filename), but I guess it's ok to have it.

Yeah, true, although I was imagining the uid would be used as the primary file identifier in the `file` endpoint. So a file with uid `GnSiQs9_NEl2BU0s4C1` would be downloaded from `/file?uid=GnSiQs9_NEl2BU0s4C1` with the filename "<original_filename>_GnSiQs9_NEl2BU0s4C1" (we can convert filenames back to their original on download probably)

**Comment by CarlosNZ** [comment]
> @CarlosNZ looks great, a few suggestions:
> 
> > multipleFiles (boolean, default false -- specifies if user can upload multiple files for this question)
> 
> file limit ?
> 
> > fileExts
> 
> fileExtension
> 
> I feel like the UUID field might not be needed on the table. (server generates UUID and embeds it in the filename), but I guess it's ok to have it.
> ### Thumbnails
> 
> Default thumbnails for commons types ? (if server fails to generate a thumbnail, just uses that one ?)

Okay, have updated original post.

**Comment by CarlosNZ** [comment]
Additional refinements to be part of new issues in [Epic 41](https://github.com/openmsupply/application-manager-web-app/issues/430)
