### ISSUE TITLE
Progress bar displaying over User Area

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#304]
<img width="1136" alt="Screen Shot 2021-01-29 at 2 41 04 PM" src="https://user-images.githubusercontent.com/16461988/106220337-2437d580-6240-11eb-91ec-7124f1841f18.png">

**Comment by CarlosNZ** [comment]
Duplicate #248 ;) (You can pick which one too close)

**Comment by nmadruga** [comment]
Fixed as part of [PR #441](https://github.com/openmsupply/application-manager-web-app/pull/565)
