### ISSUE TITLE
Remove old router and files used for Application

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#369]
After all done in Sprint 22 for [Epic#21](https://github.com/openmsupply/application-manager-web-app/issues/101) we can remove previous router and Containers/Components of Application

**Comment by CarlosNZ** [comment]
And rename all the NEW ones to the original names (files and components and routes)

**Comment by nmadruga** [comment]
Need to update most components to be using ERROR_GENERIC (as started in PR #444)

New:
- ApplicationCreateNEW
- ApplicationWrapperNEW
- ApplicationSummary
- ApplicationWrapper

Continued:
- ListWrapper

Old (will get removed fully):
- ApplicationCreate
- ElementsBox
- ApplicationOverview
- ApplicationSubmission

Strings to be removed (from `constants` file):
- ERROR_APPLICATION_CREATE
- ERROR_APPLICATION_ELEMENTS
- ERROR_APPLICATION_OVERVIEW
- ERROR_APPLICATION_PAGE
- ERROR_APPLICATION_SECTION
- ERROR_APPLICATION_SUBMISSION
- ERROR_APPLICATION_SUBMIT
- ERROR_APPLICATIONS_LIST

**Comment by andreievg** [comment]
@nmadruga. The reason I've changed to generic was because there were quite a few using application_overview error, I think ideally we should change from ERROR_GENERIC to more specific (i just didn't think it was part of the PR was working on, and wanted to do a quick fix)

**Comment by nmadruga** [comment]
Ok. Regarding what is described in [comment](https://github.com/openmsupply/application-manager-web-app/issues/369#issuecomment-800693334) should only really remove `strings` that are not in use (after removing the old container/components) and verify if any remaining ERROR should be using the Generic one instead of a specific one.

**Comment by nmadruga** [comment]
Partially done by PR #470
