### ISSUE TITLE
Check for allowed page on ApplicationPage load

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-web-app#374]
Based on discussion:

- Update progress calculation to set first invalid section/page in structure.info.firstInvalidPage
- Add check to ApplicationPage to ensure the currently loading page is less than firstInvalid, and redirect to firstInvalidPage if not.
- The above 2 points need to happen for sure. Slightly less certain is if we can rely on the above check for ALL page links (Next button/Progress bar) or whether they need to implement a bit of their own additional logic first. Try it and see.

**Comment by andreievg** [comment]
> Add check to ApplicationPage to ensure the currently loading page is less than firstInvalid, and redirect to firstInvalidPage if not.

lest the or equal. isLinear

I think the name should be **firstStrictInvalidPage**

> The above 2 points need to happen for sure. Slightly less certain is if we can rely on the above check for ALL page links (Next button/Progress bar) or whether they need to implement a bit of their own additional logic first. Try it and see.

They need to set 'isStrictPage' (ifLinear etc..) and navigate to correct page (I don't think just having 'links' would do the job)

The first point about application page navigation, is a safe guard, but not complete solution.

Just remembered there is a point about this in the diagram:
![Screen Shot 2021-02-25 at 1 33 44 PM](https://user-images.githubusercontent.com/26194949/109085257-338e3e00-776e-11eb-8599-4e9dc275ea49.png)
