### ISSUE TITLE
Update useGetReviewStructure to add reviewResponses for lvl 2 consolidation first review

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#390]

**Comment by andreievg** [comment]
Would need to add `LatestPreviousLevelResponse`, `ConsolidationProgress`, `firstNotDoneColsolidationPage`,`canSubmitAs` calculations.

During review work, we've added some helpers for `actions` on review home, these will also need to be updated for consolidator.

Some diagrams for reference:
https://app.diagrams.net/#G1RRcvqdU2ZXR0F_gVAWknO_94kLR2pbah
https://app.diagrams.net/#G12_fvjjn_dr7YbwR-z-2_g_QI0tnS13nf
https://app.diagrams.net/#G1gAJrF1S2xrg-tZrzKxJNqV9Mtul096zZ

**Comment by andreievg** [comment]
this seems like a more natural transition:

https://app.diagrams.net/#G10qb2_JN9SeL6JkNBjk7bOR3ond76NFUn

![Level 2 Review Structure Changes (1)](https://user-images.githubusercontent.com/26194949/115547077-f1aaef80-a2f9-11eb-8385-e215ad15169e.png)
