### ISSUE TITLE
Rename hook useGetFullStructure to useGetApplicationStructure

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#396]

**Comment by nmadruga** [comment]
@andreievg and @CarlosNZ just wondering do we want to have these names for the hooks?
- `useGetApplicationStructure`
- `useGetReviewStructure`

I saw in the latest structure diagrams that Andrei have mentioned `useGetFullApplicationStructure` so just wanted to make sure this issue would be renaming to what we have agreed. Event though this should be probably moved to "Next sprint pre-selection" so we don't get too many conflicts in new PRs.

**Comment by andreievg** [comment]
as per: 

we should rename useGetReviewStructure to useGetReviewStructureForSections (or something similar)

**Comment by nmadruga** [comment]
@andreievg & @CarlosNZ I have updated the hooks from-to:
useGetFullReviewStructure => useGetReviewStructureForSection
useGetFullApplicationStructure => UseGetApplicationStructure

About to create a PR for this now (based on yesterday clean-up PR #568)

Should I also rename the type `FullStructure` to `Structure` or leave it as it is?

**Comment by nmadruga** [comment]
Oh! A reminder to Andrei (when working on publishing the docs related to Consolidation/Assignment to our wiki) that these method names will also need to be updated on the docs.
