### ISSUE TITLE
Duplicate Review Responses

### ISSUE THREAD

**Issue by andreievg** [openmsupply/application-manager-web-app#423]
When review is restarted (due to either any reason like 'changes requested', application re-submission etc.), we need to duplicate the responses;

As per diagram `Responses Flow`.

~~Should break this into two issues:~~
~~- [ ] Level 1 reviewer~~
~~- [ ] Level above 1~~

`Level 1 reviewer` ->

* look at all of the latest application responses (submitted application responses) that are assigned to reviewer
* if latest application responses has a 'draft' review_response attached to it for this reviewer, don't do anything
* if latest application responses doesn't have a review_response attached for this reviewer, add an empty one
* otherwise duplicate review_response

~~`Level 2 reviewer` ->~~ MOVED to issue #295

~~* look at all of the latest review_response from review that have status == submitted (not review_responses that are status submitted)~~
~~* same logic as above but for review_response~~

**Comment by nmadruga** [comment]
Should we move this to be done in issue #295 (Part of different Epic - [Consolidate reviews](#165))

> Level 2 reviewer ->

> look at all of the latest review_response from review that have status == submitted (not review_responses that are status submitted)
> same logic as above but for review_response

**Comment by andreievg** [comment]
Yep i think Level above one should be a seperate issue in Consolidation
