### ISSUE TITLE
UI to show to applicant that changes are requested (Application home page)

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#437]
Changes to the Application home page to display buttons to "Update" sections with "Changes required" (from LOQ) and display progress on the Application after the Applicant clicks on the Update button to start to **make changes**.

## Designs
![Screen Shot 2021-03-15 at 2 48 08 PM](https://user-images.githubusercontent.com/16461988/111093974-15fb0a00-859f-11eb-8c37-45cbb959012a.png)
![Screen Shot 2021-03-15 at 2 46 48 PM](https://user-images.githubusercontent.com/16461988/111093978-17c4cd80-859f-11eb-9a05-c7b95277c4f3.png)

**Comment by andreievg** [comment]
@nmadruga awesome thanks.

- [ ] Part 1 - Add helpers to structure, as per : https://app.diagrams.net/#G1gzlvn8D9ulQP8baqo93qspjsQqEDlxOa
- [ ] Part 2 - Add UI elements

For part 1:

![Screen Shot 2021-03-15 at 5 53 42 PM](https://user-images.githubusercontent.com/26194949/111105270-7dbd4f00-85b7-11eb-8e26-bf733af0d4ba.png)

![Screen Shot 2021-03-15 at 5 54 05 PM](https://user-images.githubusercontent.com/26194949/111105283-82820300-85b7-11eb-9844-182087599ea9.png)

**Comment by andreievg** [comment]
@nmadruga I haven't assigned myself to this one, but did the first part (second part is open if you want to do it, i am going to do the https://github.com/openmsupply/application-manager-web-app/issues/314, as a prerequisite to https://github.com/openmsupply/application-manager-web-app/issues/441)

**Comment by andreievg** [comment]
this PR: https://github.com/openmsupply/application-manager-web-app/pull/447, under testing, will give an idea what needs to be done for part 2

**Comment by nmadruga** [comment]
I'll assign this to me then, should start right after looking at some review today.
