### ISSUE TITLE
Make sure context state of questions and responses is changed when response is written to cache

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#44]

**Comment by andreievg** [comment]
(btw) context state = result of useGetResponse, I'll call it applicationState for now.

The way I see this working:

When navigating to page (ApplicationStep), we do useGetResponsesByCode for an application, and store in applicationState (hook)

Pass that applicationState to each ApplicationViewWrapper. Also each ApplicationViewWrapper get initialValue from it.

onUpdate method from ApplicationViewWrapper is handles in (ApplicationStep), it does two things:

* Write new response value to cache (make sure we don't refetch application)
* Update applicationState with appropriate value

This would cause new prop (applicationState) to be passed to ApplicationViewWrapper (to check visibility etc)
