### ISSUE TITLE
Mutate application from cache.

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#45]
Need to decide when

**Comment by nmadruga** [comment]
Based on what I was researching on issue #37 storing the responses in the cache to be sent to the server only on a particular event isn't a common design pattern while using Apollo client. It seems better to continue sending the responses to the server as soon as the response is changed - and do other things to manage how the UI performances better for low latency users. The way to do this (from what I have found so far) is using:
- [Optimistic UI](https://www.apollographql.com/docs/react/performance/optimistic-ui/) to render a pseudo result from the server immediately after sending it to the server - than waiting for the server response to render the component.
- [HTTP Batch Link](https://www.apollographql.com/docs/react/api/link/apollo-link-batch-http/) to batch queries and mutations to be send to the server in a batch (in internals) - this is done for the entire App from what I understood. So, we can postpone adding this to make sure that's what we want - and it would work well for other queries (ex: load application - we don't want to wait for to long to get this result from the server) and decide if that's what we want.

**Comment by andreievg** [comment]
I am ok with just doing mutation for now. 

With Optimistic UI, it’s not guaranteed that server receives the data, so we would need to send the whole application on submit, is that right ?

HTTP Batch Link can be the way to go, but not sure if we can have full control of the flow (you've mentioned that already)

I was soo convinced that this workflow of storing to cache and then updating from cache was in built to Apollo, as it seems like the main use case for such a tool.

Btw graphile does allow the following:

```
mutation MyMutation {
  mutation1: updateApplicationResponse(input: {patch: {value: "yow"}, id: 1}) {
    clientMutationId
  }
 mutation2: updateApplicationResponse(input: {patch: {value: "sup"}, id: 2}) {
    clientMutationId
  
  }
}
```

**Comment by andreievg** [comment]
I've mentioned a couple of time that we shouldn't do dynamic queries, now I think it might be the best option (also would make creating application logic nicer)

**Comment by nmadruga** [comment]
> With Optimistic UI, it’s not guaranteed that server receives the data, so we would need to send the whole application on submit, is that right ?

That's a good idea. I'll work on that in this PR. I'm not sure yet how Optimistic UI would work, but I think it might give some error if the response wasn't send to the server. Anyway I like the idea of sending the full application at the end.

**Comment by nmadruga** [comment]
> I've mentioned a couple of time that we shouldn't do dynamic queries, now I think it might be the best option (also would make creating application logic nicer)

The problem is that one thing depends on the other. That's why we are using `callbacks` for now.
- Create a new `Application` - a new `id` is generated in the server
- Create 1-N `ApplicationSection` with foreign key to new `Application.id`
- Create 1-N `ApplicationResponse` with foreign key to `Application.id`

It is possible to generate a mutation to do that, using nested creations... but would that be the best?
