### ISSUE TITLE
Bug: icon image in Footer not showing up

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-web-app#450]
None of the obvious options seem to fix this, although I'm sure it's fairly trivial with a bit of thought.

Just putting this here so we remember to get round to it at some point.

![Screen Shot 2021-03-17 at 10 41 29 AM](https://user-images.githubusercontent.com/5456533/111383671-68f2cf80-870d-11eb-81d3-bc74fc6aef66.png)

**Comment by nmadruga** [comment]
I think this is fixed! Latest PRs is showing the icon there:
<img width="1153" alt="Screen Shot 2021-04-13 at 4 52 15 PM" src="https://user-images.githubusercontent.com/16461988/114498692-a862fc00-9c78-11eb-8ce4-19c3c8cf043a.png">

I'll move to IN PR and we can close once it's confirmed (after merged current PRs)

**Comment by CarlosNZ** [comment]
> I think this is fixed!

Cool, thanks.
