### ISSUE TITLE
Update Radio plugin: option for "Other" field

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#488]

**Comment by CarlosNZ** [comment]
Question: do you think we should build this functionality into the RadioChoice plugin, or just have template add an additional "shortText" whose visibility is set to show if "Other" is selected in previous RadioChoice?

(i.e. we can already do this with existing functionality by configuring the template -- so is it worth adding more complexity to plugin?)

**Comment by nmadruga** [comment]
Using the solution that you proposed is already implemented on Drug Registration latest PR (back-end#270 link), and I agree it's not a priority. But it seems to me that having an optional (for common use of types) would be a nice to have. Considering how the config is done to add a separate `shortText`  with visibility criteria it seemed reasonable to have a an extra configuration for the `radioChoice` plugin. Also for layout purpose.

Another idea is to have extension of an elementPlugin and we could also make the complexity of adding something like that separated from the basic element.
