### ISSUE TITLE
Setup to use pre-defined colour of stage label 

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#561]
Now the colour of the stage label is getting set on the ReviewPage hardcoded checking if label == **Assessment** or else. The colour to display on the label (ReviewPage and List) needs to be  setup with a colour for each Stage name (which is swet dynamically per template). How we will do this needs to be defined by this issue.

<img width="933" alt="Screen Shot 2021-04-07 at 11 30 55 AM" src="https://user-images.githubusercontent.com/16461988/113790147-c6ba8a80-9794-11eb-89b3-0d7ba93db22b.png">

**Comment by CarlosNZ** [comment]
I'll do this as part of List styles #592.

I'll add a "colour" field to the stage table, which stores a hex value (will have default blue perhaps) and this will be read by front-end and styled in-line.
