### ISSUE TITLE
Bug: Add stage to Company Registration application (not showing on the list)

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#579]

**Comment by CarlosNZ** [comment]
I've done this (well doing) as part of my back-end changes for "[Add logo](https://github.com/openmsupply/application-manager-server/issues/293)"

**Comment by nmadruga** [comment]
Yey! Changing to Sprint 27 and moving to In PR

**Comment by CarlosNZ** [comment]
This is done and merged to master now.
