### ISSUE TITLE
Global font and colours

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#586]
Update colour variables to be used for all semantic component that we have (considering button, borders, validation, background etc). Update `site.variables` with all font styles to use ones defined in vision. Add font definition from google to `index.html` (have a look in demo-22-03) - and choose the weight based on what is in inVision: https://debs181572.invisionapp.com/overview/Drug-registration-app-V2-ckmfpptbx008401xqfx1j17ha/screens

Add media query for mobile vs desktop on each style added globally

![image](https://user-images.githubusercontent.com/16461988/114343114-53a87e00-9bb1-11eb-9450-f176bcdc40ef.png)
![image](https://user-images.githubusercontent.com/16461988/114343115-560ad800-9bb1-11eb-888f-00120c92cc21.png)

**Comment by CarlosNZ** [comment]
I will start doing this, but I'm happy to pass it over or split it out if it's taking too long.
