### ISSUE TITLE
Change validation on User Registration to allow 6 digits

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#589]

**Comment by CarlosNZ** [comment]
Do you think we need this? It's fine if passwords that already exist don't meet the current criteria on the form, isn't it? If we change the passwords requirements for a real template, we wouldn't then expect existing users to all change their passwords (except when they go to update them).

Just wondering what problem this would solve.

**Comment by nmadruga** [comment]
Yes, that's correct. This was just something that came up during one of our meeting, some of us said that it would be good to have the new user created using the same password that allow us to quickly swap to the new user, so we could test it. But that's not for a real user registration. It would definitely need a password with better safety protocol (such as having number and special characters included)
