### ISSUE TITLE
Create version for demo to Billy & Valerio with only 2 templates: User Rego and Drug Rego

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#590]

**Comment by CarlosNZ** [comment]
Why not Create and Join org as well?
And also probably Feature Showcase, since that gives a clear demo of what can be done with more complex logic, etc. If they want to create something new, they'd probably want to start by copy-pasting elements from Feature Showcase.

**Comment by nmadruga** [comment]
Good point. This was just an old note that I thought would be good to transform into an issue to be done this Sprint as part of the Epic#86. I think you are right, we will be including all existing templates (besides TestReview) as part of the demo. To be confirmed with @andrei before updating this issue title.
