### ISSUE TITLE
Update layout and use global styles: Login page

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#591]
Remember: Before changing styles take a screenshot on current page and add which style to use on each element - post to the issue so others can have a look and agree.

Just change elements with existing style. Anything not defined should be done in another (to be created) issue.

**Comment by CarlosNZ** [comment]
Screenshots from Invision board:

<img width="1155" alt="Screen Shot 2021-04-28 at 10 08 40 PM" src="https://user-images.githubusercontent.com/5456533/116387022-78b61580-a86e-11eb-80ad-ea722a9cddd7.png">
<img width="701" alt="Screen Shot 2021-04-28 at 10 08 54 PM" src="https://user-images.githubusercontent.com/5456533/116387040-7eabf680-a86e-11eb-843c-4656671c15f1.png">
<img width="778" alt="Screen Shot 2021-04-28 at 10 09 05 PM" src="https://user-images.githubusercontent.com/5456533/116387049-81a6e700-a86e-11eb-895f-bf391aaf1299.png">
