### ISSUE TITLE
Update layout and use global styles: Application page + Progress Bar

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#594]
Remember: Before changing styles take a screenshot on current page and add which style to use on each element - post to the issue so others can have a look and agree.

Just change elements with existing style. Anything not defined should be done in another (to be created) issue.

**Comment by CarlosNZ** [comment]
FYI -- I'm doing this, but I'll need to split it into two PRs. I'm nearly done with Application page, but Progress bar (sidebar) will be quite a bit more fiddling around, so I'll PR the first part shortly
