### ISSUE TITLE
Update layout and use global styles: Application + Summary + Template question plugins

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#600]

**Comment by CarlosNZ** [comment]
Any ideas how to format the textInfo element? The current `<Message>` component doesn't seem right:
<img width="543" alt="Screen Shot 2021-05-06 at 10 22 13 PM" src="https://user-images.githubusercontent.com/5456533/117283044-83e5f280-aeb9-11eb-8c43-1d6ff53d90d3.png">

And yet with nothing around the page looks bland and the info doesn't stand out:
<img width="512" alt="Screen Shot 2021-05-06 at 10 22 59 PM" src="https://user-images.githubusercontent.com/5456533/117283159-9fe99400-aeb9-11eb-9525-f24eac182011.png">

@andreievg maybe you could also ask Deb for some ideas for this?

**Comment by CarlosNZ** [comment]
Thinking of just adding a "style" parameter to textInfo, which selects which type of "Message" box to show it in (See https://react.semantic-ui.com/collections/message/#variations-info)

"style" can take the following values:

- `none` (no Message box, just markdown formatting)
- `basic` (grey)
- `info` (blue)
- `warning` (yellow)
- `success`/`positive` (green)
- `negative`/`error`

**Comment by CarlosNZ** [comment]
Implemented with #680
