### ISSUE TITLE
Front-end query server to get template types and actionables (based on template type) that the current user is allowed and display on App navigation

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#64]

**Comment by nmadruga** [comment]
The UserArea - that is currently listing all users in the system - can be used to set the `current` user. This can be an easy way to check if we are correctly setting the list of available options based on the user permission.

**Comment by andreievg** [comment]
Relocating this one to epic 11

**Comment by andreievg** [comment]
Thought to break this issue up to just get the user permissions. Actually displaying allowable applications can be done in the layout & menue epic.

Also instead of name, it would be good if template in permissions is keyed by code
