### ISSUE TITLE
Define how front-end request the list of templates and actions for the current user

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#65]
Find out and define (suggest any computed columns that might be needed) what needs to be retrieved from the server (with JWT) for the Front-end to use: template types, actions the user can make per template type, current user and current company.

**Comment by andreievg** [comment]
Front end needs to know the following things (maybe more, but these are the main ones for now)

1 - What application types are available to the user, under which policy type (apply, assign, review, consolidate ?)

2 - What sections of an application and stage can be assigned to which user.

### 1 - Types and Policies

This one needs to be know at the start, should be stored in a context at top lvl, this can persist.

Also should be available when validating user log in (first thing when page loads). 

(TODO: link to issue about login flow)

Response: 

```JSON
{
  "applicationType": [ 
       {
            "permissionType": "type",
            "stage": "number",
            "anything else"
       }
  ]  
}
```
i.e.
```JSON
{
  "updateUserDetail": [ 
       {
            "permissionType": "apply"
       }
  ] ,

   "drugRegistration": [ 
       {
            "permissionType": "review",
            "canConsolidate": "true",
            "stage": 1,
            "level": 1
       },
       {
            "permissionType": "review",
            "canConsolidate": "false",
            "stage": 2,
            "level": 1
       }
    ]   
}
```

#### Api endpoint:

/login
/validLogin

### 2 - Sections/Stage -> Reviewer

When assigner tries to assign a section on a stage to a user, they should have correct user list.

I think the query of who can be assigned what section in current stage, should happen when assign view is opened on an application.

Response can be as follows (response is based on application current section)

```JSON
{
  "sectionCode": [ 
       {
            "userName": "John",
            "userId": "123"
       }
  ] 
}

```
#### Api endpoint:

/reviewers/${applicationId}

**Comment by andreievg** [comment]
https://app.diagrams.net/#G18be7_OWNSBpukYPoKpE6SWodp_YvHB1S

![Permission Flow Front End](https://user-images.githubusercontent.com/26194949/98600504-87515480-2342-11eb-8375-39b75025759a.png)
