### ISSUE TITLE
Quick fix: List layout issue (Edit draft)

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#661]
![Screen Shot 2021-05-04 at 11 44 53 AM](https://user-images.githubusercontent.com/16461988/116946519-6c96e180-acce-11eb-9bd1-ad663f5ba832.png)

**Comment by CarlosNZ** [comment]
Done with #684 (see [comment](https://github.com/openmsupply/application-manager-web-app/pull/684#discussion_r630585599))
