### ISSUE TITLE
Display application View page when click an application with Submitted status

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#68]
Not to do the collapsable sections yet!
Just show all the sections. Use summary page and hide buttons and edit options.

**Comment by CarlosNZ** [comment]
One thing to probably squeeze into this issue (or make a new one) -- the Summary page should also respect the `isVisible` status. I notice it's currently showing ALL questions, even the ones that were hidden on the actual form.

**Comment by nmadruga** [comment]
Still missing a few things on this one to be completed:
- Summary page (after application is submitted) shouldn't show the `Submit` button not the `edit` sections links.
- One thing to probably squeeze into this issue (or make a new one) -- the Summary page should also respect the isVisible status. I notice it's currently showing ALL questions, even the ones that were hidden on the actual form.
