### ISSUE TITLE
Bug - when filling a User Registration the sticky aren't looking good

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#686]
<img width="752" alt="Screen Shot 2021-05-10 at 12 48 40 PM" src="https://user-images.githubusercontent.com/16461988/117592942-9482bb00-b18e-11eb-8cf6-3c232f756df9.png">

**Comment by CarlosNZ** [comment]
Okay, have just added a small extra tweak to existing PR #678 that takes care of this.
