### ISSUE TITLE
Bug: AssignmentJoin created after submission of updated application with changes-required on Stage 1

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#690]
Tested using existing config for Application: http://localhost:3000/application/23456/review

- Logged in as **Reviewer1**, and just declined 1 response, then submitted with LOQ back to applicant
- Logged in as **Nicole**, made the change required and re-submitted the application. You should see already the wrong new Assignment joins created (Filter by everyone on the http://localhost:3000/application/23456/review)
- Logged in as **Reviewer1** and approve all, so now it will change to the next Stage - Assessment.
- Logged in as **Valerio** (Filter by Screening) and you can see that the Review can be `Self-Assigned`

<img width="768" alt="Screen Shot 2021-05-12 at 11 18 41 AM" src="https://user-images.githubusercontent.com/16461988/117896382-8bbbf180-b314-11eb-848e-096117edccab.png">

**Comment by andreievg** [comment]
@nmadruga good find.

Would suggest, for anyone fixing this issue to first check if this can be replicated with a new application

**Comment by CarlosNZ** [comment]
PLease check if bug still exists

**Comment by nmadruga** [comment]
@CarlosNZ yes, still happening! I'll see if I can fix this one now : )

**Comment by CarlosNZ** [comment]
@nmadruga -- is there are linked PR for this, or can it be closed?
