### ISSUE TITLE
Restructure docs folder structure

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-web-app#7]
1. Remove top-most `Home.md` file and rename `internal/Home-Internal.md` back to `internal/Home.md` (This will automatically make it the wiki "home" page.
2. Exclude `external` folder from being pushed to the wiki.
3. Create `_Sidebar.md` to show the document structure.

**Comment by nmadruga** [comment]
Agreed.

**Comment by CarlosNZ** [comment]
Done in #8
