### ISSUE TITLE
Inline decision - only shows when click Review and has a Submit button to collapse

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#706]
Check out this [comment](https://github.com/openmsupply/application-manager-web-app/pull/695#discussion_r630914944) to move  the updateQuery to be a hook

**Comment by CarlosNZ** [comment]
> Check out this [comment](https://github.com/openmsupply/application-manager-web-app/pull/695#discussion_r630914944) to move the updateQuery to be a hook

I'm not clear on this -- updateQuery is already part of the `useRouter` hook, along with getParams, push, replace, etc. That's where it should stay, right?

**Comment by CarlosNZ** [comment]
Latest Miro designs:
![Screen Shot 2021-05-31 at 12 48 38 PM](https://user-images.githubusercontent.com/5456533/120125892-8dd7e880-c20e-11eb-97d7-7d3187546575.png)
