### ISSUE TITLE
Revise Review page progress if needs to differentiate between "pending" and "changes_requested"

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#709]

**Comment by andreievg** [comment]
https://github.com/openmsupply/application-manager-web-app/issues/711 should help with this (might even solve it)

**Comment by nmadruga** [comment]
Something not exactly related, but would be good to get a consensus is about what labels to show over progress...

Currently this is what is showing:

### Consolidator
* Colour: **Red** if one is Disagreed, **Green** if all Agreed
* Labels: give different feedback depending on consolidator agreement/disagreement (not good because inconstant...
  - "(X) approved (Y) declined" - based on `originalReviewResponse` decision if all **Agreed** by consolidator:
![Screen Shot 2021-05-26 at 9 59 08 AM](https://user-images.githubusercontent.com/16461988/119574285-9ba1fe00-be09-11eb-9cc9-a45b39b90448.png)

  - "(W) disagreed (X+Y) agreed" - based only on consolidator decisions:
![Screen Shot 2021-05-26 at 10 03 43 AM](https://user-images.githubusercontent.com/16461988/119574772-13702880-be0a-11eb-96bf-334d4536a4e9.png)

### Reviewer
* Colour: **Red** if one is Declined, **Green** if all Approved
* Labels: 
  - "Completed" - based on reviewer decisions if all **Approved**: <img width="704" alt="Screen Shot 2021-05-26 at 10 11 34 AM" src="https://user-images.githubusercontent.com/16461988/119575215-c93b7700-be0a-11eb-9374-56e5b9b759ed.png">

  - "(X) declined" - based on reviewer decisions one at least one is **Declined**: <img width="704" alt="Screen Shot 2021-05-26 at 10 07 57 AM" src="https://user-images.githubusercontent.com/16461988/119575210-c771b380-be0a-11eb-85d8-351fc3a48b57.png">

  - Empty - when all is **Approved** but not finished yet: <img width="704" alt="Screen Shot 2021-05-26 at 10 11 14 AM" src="https://user-images.githubusercontent.com/16461988/119575217-ca6ca400-be0a-11eb-9dc2-3c4297492a0b.png">
