### ISSUE TITLE
Bug: Trying to click "review and submit" button after going to summary and then back with Edit the button stop not working

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#717]
Seems to occur on some templates, not sure exactly which, but UserEdit and OrgRego have been shown to be affected

steps:
1. create new EditUser template, without changing the password. And go to the summary page
2. Click on edit the option to use the password, going back to page 1. Don't change anything
3. Try clicking on "Review and submit" doesn't work
4. Try just focusing on any field and try to clicking the button again. It works... 
5. Mistery 🤔

**Comment by CarlosNZ** [comment]
Is this with the latest changes in #701 (and back-end complement) ?  Cos I can't seem to reproduce it.

**Comment by CarlosNZ** [comment]
Ah I see it now. However, it's not just UserEdit, I can create the same situation in RegisterOrg (and probably others). I'll update the issue title to reflect this

**Comment by CarlosNZ** [comment]
It's also affecting the "Next" button, but only on "linear" restricted templates.

I notice that I can click "Next", nothing happens, then as soon as I change one of the responses, the page jumps to the next page, without the button needing to be clicked again.

I can see that it's getting stuck waiting for the "requestRevalidation" method to complete. I think the logic around `shouldProcessValidation` and `lastRevalidationRequest` must be getting messed up somehow.

**Comment by CarlosNZ** [comment]
@andreievg -- maybe you want to have a look into this one, as I think it might be to do with the "FormElementUpdateTrackerState" module. Not sure, but it's becoming quite a noticeable problem with the new Laos templates we're working on.
