### ISSUE TITLE
Option on RadioChoice plugin to display inline

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#750]
When there are less options to select by the user, the UI looks cleaner with radio vertically aligned  in one line as per latest designs - for List builder:
![Screen Shot 2021-05-31 at 11 16 09 AM](https://user-images.githubusercontent.com/16461988/120123619-fd94a600-c203-11eb-9de1-8e061651b5fa.png)

**Comment by CarlosNZ** [comment]
FYI - **Checkbox** element currently has the parameter `layout`, with an `inline` option, so should probably follow same convention and possible even the code structure.

**Comment by CarlosNZ** [comment]
Also -- do you think it should be somewhat automatic -- so if there's only two options, it goes "inline" by default?
