### ISSUE TITLE
Option on ShortText plugin to have maxWidth

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#751]
Default should be kept to show in full width, but if the new field `maxWidth` is defined show as defined in the question plugin of shortText.
e.g.:  Quantity (number) field in the design.

As per in latest designs:

![Screen Shot 2021-05-31 at 11 20 36 AM](https://user-images.githubusercontent.com/16461988/120123717-96c3bc80-c204-11eb-933d-6b623c6a2938.png)

**Comment by CarlosNZ** [comment]
Fixed with #755
