### ISSUE TITLE
Flickering sections on application summary

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#775]
<img width="1154" alt="Screen Shot 2021-06-10 at 12 54 11 PM" src="https://user-images.githubusercontent.com/16461988/121448085-10209380-c9eb-11eb-84c8-b6f8d9bb1513.png">

Ah, the picture is not showing it, but happens when crossing 2 sections. It just keeps both at a flickering state. Weird.

**Comment by nmadruga** [comment]
Happened during demo : P

**Comment by CarlosNZ** [comment]
Fixed during recent bunch of UI improvements (#885)
