### ISSUE TITLE
Improve error handling ui on elements

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#784]
Update wrapper to have a generic error state to be showing when invalid question or changesRequested to Applicant - for changes requested it needs a second state to show in the comment in grey after changed

**Comment by CarlosNZ** [comment]
I have some thoughts on this, also regarding Custom validation in plugins which complicates it -- will discuss when Andrei is back, but I think we need to resolve a couple of things before going ahead with this.
