### ISSUE TITLE
Bug: Applicant can't start updating application after Changes-required after a second-review (when consolidator had disagreed previously with decision)

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#796]
The list show action for applicant to **Update** their responses but in Application home page there is no Update button, therefor the application cannot be started.

**Comment by nmadruga** [comment]
This example shows an example of the bug happening with Application "34567" after review had a `disagreement`, changed by reviewer1 to `non-conform` and then `agreed` before being submitted with `LOQ` to applicant:
<img width="642" alt="Screen Shot 2021-06-16 at 11 36 27 AM" src="https://user-images.githubusercontent.com/16461988/122308926-75333680-cf61-11eb-946f-0e3e8c38d336.png">
<img width="746" alt="Screen Shot 2021-06-16 at 11 37 37 AM" src="https://user-images.githubusercontent.com/16461988/122308918-72384600-cf61-11eb-85c1-1836935ab602.png">
<img width="762" alt="Screen Shot 2021-06-16 at 11 37 08 AM" src="https://user-images.githubusercontent.com/16461988/122308921-74020980-cf61-11eb-800a-8bc951770c5f.png">
<img width="744" alt="Screen Shot 2021-06-16 at 11 36 56 AM" src="https://user-images.githubusercontent.com/16461988/122308924-749aa000-cf61-11eb-86d1-d3316ea7bd14.png">

**Comment by andreievg** [comment]
I think it would be to do with this one: 

https://github.com/openmsupply/application-manager-server/blob/b5e6b324bf4a3a866dee4107288c003555072915viewResponse.ts#L47-L51

Since reviewResponse doesn't have originalReview response (can pass it through from structure)

**Comment by nmadruga** [comment]
Nice. Seems to be a quick fix then. I'll change to this Sprint, and see if I can work on a fix today : )
