### ISSUE TITLE
Bug -- "Review" link appearing on Re-review even for unanswered (NULL) questions

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-web-app#804]
Please see discussion from [this comment onwards](https://github.com/openmsupply/application-manager-web-app/pull/791#issuecomment-865415337) for description of the problem and how to reproduce.

Suspect something wrong in the logic of whether to display `<ReviewElementTrigger>` (in "ReviewApplicantResponse.tsx")

**Comment by nmadruga** [comment]
I have quickly investigated this today, but it seems to be a bigger problem than just in UI. The `generateReviewAssignment` is not doing good, after the application is re-submitted it is considering this is a "First review assignment", which isn't...
I'll investigate further. I also noticed there is a problem with the application not showing on the list for the reviewer assigned, it shows after it has been assigned (by Assigner) and doesn't show once application is re-submitted by applicant.

**Comment by nmadruga** [comment]
Have continued investigation on this, the problem seems to be created on `useRestartReview`, when used for re-start of Review (which isn't a consolidation) after changes-required to the applicant were made, it created all reviewResponses which includes the ones with NULL applicationResponses.

**Comment by CarlosNZ** [comment]
Yikes -- thanks for looking into this.
