### ISSUE TITLE
Progress Bar 'state' logic

### ISSUE THREAD

**Issue by andreievg** [openmsupply/application-manager-web-app#81]
## Description
**From what was discussed in the team meeting on 17/11/2020**
**EDITED on 24/11/2020**: Considering what was discussed in the comments: [1](https://github.com/openmsupply/application-manager-web-app/issues/81#issuecomment-728671725), [2](https://github.com/openmsupply/application-manager-web-app/issues/81#issuecomment-728679792)

## Summary
* Template should have a flag to indicate if application should follow a `linear` progress.
* Indication on the Progress bar for sections/pages (and section icon has the combination of pages' statuses):
  - **neutral** => number for sections, empty space for pages
  - **valid** => <img width="23" alt="Screen Shot 2020-11-17 at 1 05 54 PM" src="https://user-images.githubusercontent.com/16461988/99323011-1677e280-28d6-11eb-88a2-f844e1d14438.png">
  - **invalid** => <img width="24" alt="Screen Shot 2020-11-17 at 1 05 50 PM" src="https://user-images.githubusercontent.com/16461988/99323510-45db1f00-28d7-11eb-80a2-c7d5d7e922bc.png">

## Terminology
When validation a page, will do either:
  - **regular** validation: Only check non-empty elements in the page
  - **strict** validation: Check for all elements in the page

#### Loading page 
- Runs **strict** validation for previous pages.
- Progress bar should only show **valid** icon for previous pages. And **neutral** icon for current page.
- **[TODO #135]** Redirects to last page that has invalid or unanswered elements - if there is one.

#### Navigation box
- Can only go to the some next page when all responses in current page are valid. 
- **[TODO #136]** When click "Next" => validates the current page
   - Show problems inside page for ALL elements (even unanswered)

#### Progress bar
- Next pages and sections are disabled
- After clicking Next, before moving to the next page:
   - If current page is valid (all required responses answered & no invalid elements) - show **valid** icon
   - Show **neutral** icon on the new current page
- Previous pages are enabled so user can click to go back
  - When changing some response on a previous page that makes it invalid -- it doesn't let you go forward until its corrected (even though the later page might still show "Valid")

#### Summary page
- can't get to it unless all pages are valid (i.e. same logic as all pages)

#### Loading page
  - Checks All pages that have some elements that have been responded to (i.e. NOT undefined)
  - Show indication in progress bar for pages that have elements answered (OR all elements are valid - in case no element is required in the page):
    - If page is valid (all required responses answered & no invalid elements) - show **valid** icon
    - If page is invalid (at least one invalid element) - show **invalid** icon
    - All other pages show the **neutral** icon

#### Navigation box
- Can go to next pages using "Next" or clicking on another page in the Progress bar.
- When click "Next" (or in another page) => **strict** validation of the current page
- Go to the new current page regardless of the validation status of previous page.

#### Progress bar
- Current page/section always show the **neutral** icon
- When clicking on other page => Run **strict** validation of the current page
- Go to the new current page regardless of the validation status of previous page.
- Show indication for previous pages:
  - If page is valid (all required responses answered & no invalid elements) - show **valid** icon
  - If page is invalid (all required responses answered & at least one invalid element) - show **invalid** icon
  - All other pages show the **neutral** icon

#### Summary page
* **[TODO #48]**
- Only show problems in each section for invalid answered elements at the start 
- Required elements that haven't been answered - would only show empty and the * to identify it's required.
- After clicking on the **Submit** button:
  - If all required elements are answered with valid responses & no other invalid elements - Show message to confirm the submission indicating that after submitted the application can't be changed.
  - If any required responses is empty or any invalid elements - Show message saying there are problem in the application
    - Run validation over ALL elements and show problems (even for required unanswered elements)
    - Going back to a section should show all problems now
    - The progress bar will show icons for all pages:
      - If all required elements have valid responses & no other invalid elements - show **valid** icon.
      - If at least one element has an invalid response - show **invalid** icon.
   - NOTE: this "submittedClicked" status is for the current session only -- if page is refreshed or visited later, it will only show problems as described above.

--------
## Previous description

**Progress bar need to indicate:**
* Pages that can be visited (for 'linear view')
  - Show visited pages enabled
* Valid/Invalid pages - Icons to replace the Page number: 
  - Invalid `exclamation circle`
  - Valid `check circle`
* Set page is visited on Next button & Previous buttons

**Pages that can be visited:**

`Linear`

* Page where first isRequired and isVisible response has no value. (this should allow for gap pages, gap page is when a page becomes visible in between valid pages)
* Navigation to summary can only be done if all pages are valid

`Non-Linear`

Any page

**Valid/Invalid pages**

What is invalid page ?

For a page, all isVisible elements, that are also isRequired have a value (plugin must make sure to only send value in onUpdate event when it's valid)

`Linear`

Should be easy for this case, need to validate this page before moving to next page.

(what happens when we navigate back to page and change things that may cause validation or visibility changes in other pages ? I think rules in `Deduce by logic` should be appropriate)

`Non-Linear Problem`

We don't want to show whole form with all of the pages having invalid status form the start. So need some sort of mechanism for knowing that a page is eligible for validation indicator.

`isVisited` flag

One solutions is to use isVisited tag on a page, in local store rather than DB. Basically when user navigated to a page, and then changes page thereafter, it would be eligible for validation indication.

We would need to persist this store in order to work with refreshes, we would also need to make sure to run this check on submission (or on summary page load). When persisting this store we would need to know which record it is related to.

`Deduce by logic` (kind of a hybrid of isVisited, but without persist)

Eligible for validation, is a flag set on a page (non persistent)
* A page has at least one response
* When navigation to summary page (or on submission), we mark all pages as eligible for validation
* When navigating away from a page (on next button, on select another page in the future parts of the application)

**Comment by andreievg** [comment]
@nmadruga 

Thank you ! looks great, a couple of refinements

> Previous pages are enabled so user can click to go back
> When changing some response on a previous page that makes it invalid -- it doesn't let you go forward until its corrected (even though the later page might still show "Valid")

We can further discussion about this when we cross that road, but just one use case that we didn't talk about, to keep in mind:

In linear mode when we go to some page in the past, and edit something that will make future pages invalid. (this might need an invalid icon).

####  Updating progress bar on response save

I think the state of progress bar would update on every response save, so I think this would happen without pressing next ?

> Non linear, progress bar
> If page is invalid (all required responses answered & at least one invalid element) - show invalid icon

Since we have no isValid status on the response, I think it's ok to show invalid icon in non linear when at least one response is invalid ? So that when user navigates to a page that is not valid they can see what is not valid

**Comment by nmadruga** [comment]
I'm confused on when we decided to do this way - during the meeting we agreed that we have 3 states:
- neutral = When the page has missing required elements (not answered yet)
- invalid => All required elements have answers but some are invalid
- valid => All required elements have answers that are valid

So when you just have run the validation on ONE element in a page, from what we have decided we would show the **neutral**, but now you an Carl think otherwise? And in this case (using the `invalid` icon after validation ONE element) how would we know when do we run the validation on ALL elements in the page (and show errors) and when not to?

**Comment by nmadruga** [comment]
> I think the state of progress bar would update on every response save, so I think this would happen without pressing next ?

I think we never show the 'invalid/valid' icon on the current page. Or should we? We can check with Debb

**Comment by CarlosNZ** [comment]
> So when you just have run the validation on ONE element in a page, from what we have decided we would show the **neutral**, but now you an Carl think otherwise? And in this case (using the `invalid` icon after validating ONE element) how would we know when do we run the validation on ALL elements in the page (and show errors) and when not to?

Yeah, I thought we agreed that if there is _any_ errors on a (previous) page, then the error indicator should show for that page, regardless of whether the other elements on that page were correct or empty. That makes sense to me, as I think "error" should take priority over "neutral" -- to me "neutral" implies that it's just unfinished, but there's no errors in what's been done so far.

But it's just a priority thing (error > neutral vs neutral > error) and doesn't affect any of the other logic here. But I'm struggling to think of any real-life examples where "neutral" state would take precedence over "error".

**Comment by CarlosNZ** [comment]
> > I think the state of progress bar would update on every response save, so I think this would happen without pressing next ?
> 
> I think we never show the 'invalid/valid' icon on the current page. Or should we? We can check with Debb

Yeah, I think that's right -- the page you're on should always show "neutral" in the progress bar. It looks like that's what Deb's going for but there's no exact demo -- we'll ask her next check-in.

**Comment by andreievg** [comment]
>So when you just have run the validation on ONE element in a page, from what we have decided we would show the neutral, but now you an Carl think otherwise? And in this case (using the invalid icon after validating ONE element) how would we know when do we run the validation on ALL elements in the page (and show errors) and when not to?

I think we switched half way through, once we realised we should be storing isValid on the response. (prior to that there was no real way to check, apart from checking is required field undefined, but that would mean all of the form would automatically be invalid)

Agree it would be good to get Debs input.

> I think we never show the 'invalid/valid' icon on the current page. Or should we? We can check with Debb

Form my understanding, we would need to rethink our response state generation logic if we need to update progress bar on next press (i think generating progress bar state would be done when response is saved, or on page load)
