### ISSUE TITLE
Fix problem with timeUpdated on reviewResponses and show stages for a group of applicationResponse & reviewResponses in the History Panel

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#811]

**Comment by nmadruga** [comment]
Problem with timeUpdated has already a fix on PR #803. But the other fix to be done as part of this issue, requires a little discussion. I'm not sure how to deal with this problem. I have started a branch that gets all historyElements (which includes both Applicant response and review responses) and separate in blocks for associated `application.stageNumber` and `review.stageNumber`. For Reviews this is work well, but application has a problem. The stage returned is the current stage for the application, and not the stage when the applicant response was submitted. 

I'm thinking now to use the `timeUpdated` for each response and compare with the `timeStageCreated` to allocate each response in the correct group of history Elements belonging to a stage.

**Comment by nmadruga** [comment]
@andreievg and @CarlosNZ is the problem clear to you? And regarding the solution, do you guys think that's a good way to track which response goes in which group or do you suggest any other?

**Comment by CarlosNZ** [comment]
> I'm thinking now to use the `timeUpdated` for each response and compare with the `timeStageCreated` to allocate each response in the correct group of history Elements belonging to a stage.

Yeah, that seems like the most straightforward way to make it work. Unless we add a "stage" field to the application_response table and insert the current stage when saving responses?

**Comment by nmadruga** [comment]
> Yeah, that seems like the most straightforward way to make it work. Unless we add a "stage" field to the application_response table and insert the current stage when saving responses?

I like this idea a lot. This could be a simpler way to solve that. Thanks, I'll work on this solution after I go through some PRs today : )
