### ISSUE TITLE
View History is showing outside the group of responses the border also need to be improved

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#825]
Also, on current `master` the blue border is showing cut off at the top:
<img width="664" alt="Screen Shot 2021-07-22 at 2 45 24 PM" src="https://user-images.githubusercontent.com/16461988/126583440-bd3302a9-de8f-4ca0-8914-e3a6fa73e6da.png">

@CarlosNZ please help : D

**Comment by CarlosNZ** [comment]
Just to clarify -- the "ShowHistory" part of this issue has already been sorted elsewhere, and the problem with blue border is taken care of as part of #860 .
