### ISSUE TITLE
Hide unwanted items from the Dashboard

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/application-manager-web-app#830]
Currently a user can  access the 'Edit User Details' procedure in 2 different places. 

It would be tidier if this was just in 1 place. 

My opinion is that a classic option, such as the top menu bar or the log-in button menu would be the best place to access this type of functionality. 

So would be great if we had a way to hide unwanted items from the user in the Dashboard:

![2021-07-06_14-31-35](https://user-images.githubusercontent.com/19318937/124536781-b6d24580-de6c-11eb-9cb6-756d0f9d1c24.png)

**Comment by CarlosNZ** [comment]
Note -- relates to #829 and should be considered together.

**Comment by CarlosNZ** [comment]
Suggested solution -- templates with NULL category shouldn't show on Dashboard at all.

**Comment by CarlosNZ** [comment]
Is this done, @nmadruga ?
