### ISSUE TITLE
Add Markdown interpret for Elements plugin

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#86]
Maybe in the ApplicationWrapper we add this interpreter? Since it's going to be required for different fields in different elements. Some parameters that could be using the markdown interpret:

### Short Text Input
- **label**: `string` -- Text that shows in the HTML "label" attribute of the form element

### Text Information
- **text**: `string` -- body text to display

**Comment by CarlosNZ** [comment]
Yes, great idea, and should be easy to do. If we import it in the ApplicationViewWrapper, then we can pass it down to every plugin.

We'd probably also want it in Summary (and maybe Template) Views too, right?

**Comment by CarlosNZ** [comment]
To be done after #237
