### ISSUE TITLE
Template builder: Add core_action to send notification to Applicant

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#863]
Applicant get notified by email when "changes required" / "submitted" / "outcome changes"

**Comment by CarlosNZ** [comment]
This can't really be a "core" action, as the message in the notification/email will need to be template-specific.

**Comment by CarlosNZ** [comment]
> This can't really be a "core" action, as the message in the notification/email will need to be template-specific.

Unless we make it core action with a "placeholder" message that needs to be updated when creating the template (as we discussed IRL)

**Comment by nmadruga** [comment]
Closing after agreeing this isn't a core action, and defined per template
