### ISSUE TITLE
Bug: Need to click twice in "Review and Submit" on User registration application

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#866]

**Comment by CarlosNZ** [comment]
I don't think this is unique to "User Registration" -- its the old problem of the Button not knowing that the responses are all valid -- it's supposed to wait until the FormElementUpdateTrackerState says it's good to go, but we've never fully fixed this problem.

(If you click outside the text input field and wait a second, you'll only need to push "Review and Submit" once (as long as all responses are valid))

**Comment by CarlosNZ** [comment]
Assigning @andreievg to this, since he knows his way round FormElementUpdateTrackerState

**Comment by nmadruga** [comment]
Thank you! It would be nice if we could just try and keep this very visible bugs under control. I'm aiming for a more stable version so we can release a new demo probably next week?

**Comment by andreievg** [comment]
Hmm, diagnosed the issue and noticed that 'entered' event was proceeded by 'exited' event of previous form element. Best way to replicate is to set throttling to fast 3g, and then it's always replica-table.

There is a note about this in a diagram about validation (I don't think it made it to an issue). Basically need to track `FormElementUpdateTrackerState` by element, i'll spend 15 mins working on this now, if it goes beyond that i'll leave it for the weekend
