### ISSUE TITLE
Bug: Slight move top left and right UserArea during application creation - weird bug more apparent after loading is longer

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#868]

**Comment by CarlosNZ** [comment]
Not seeing this at the moment. @nmadruga can you check and see if you can re-produce the problem and maybe close this issue if not?

**Comment by nmadruga** [comment]
Nice. I'll have a look now to see if can replicate while testing your PR  branch `ui-improvements`

**Comment by nmadruga** [comment]
Can't see this happening anymore. Can be closed
