### ISSUE TITLE
Bug: something weird with checkboxes

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#869]
Specifically: Start a Feature Showcase application and go to the checkboxes page (S1, P4). Start toggling checkboxes in the "Lotsa boxes" question. You'll see there is quite a delay in the response, and also, sometimes they automatically switch themselves off after being selected. 

Must be something to do with how the local state "value" and the stored response are interacting with each other.

**Comment by CarlosNZ** [comment]
Eww, this is quite nasty. The query that gets the checkbox array is running over and over causing the element to keep re-rendering.

Will fix ASAP
