### ISSUE TITLE
Bug: Stage filter disappearing from list after clicked

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#874]
1
<img width="194" alt="Screen Shot 2021-07-28 at 3 06 13 PM" src="https://user-images.githubusercontent.com/16461988/127257354-6dfbf385-6a06-42e1-affb-72a4df9900af.png">
2 - Filter box closes, but nothing added on the filters list
<img width="385" alt="Screen Shot 2021-07-28 at 3 06 20 PM" src="https://user-images.githubusercontent.com/16461988/127257360-6296dc3f-faa7-4368-8c4c-6ee5e1628e24.png">
3 - Stage filter is now gone!
<img width="189" alt="Screen Shot 2021-07-28 at 3 06 24 PM" src="https://user-images.githubusercontent.com/16461988/127257363-27309b73-3925-4765-845f-7335eddb8343.png">

No errors on Console

**Comment by nmadruga** [comment]
Originally I tested with a list that only had one application and 1 stage (application was in first stage), and though could be correlated. But now tested again with more applications and in different stages and it seems to be always a problem.

**Comment by andreievg** [comment]
Thanks for spotting this, look like I missed it in this commit (when changing from if statements to switch): https://github.com/openmsupply/application-manager-web-app/pull/799/commits/fa1860d3aca2cd4f8b3bc2473e1220ef920021c8

**Comment by nmadruga** [comment]
Cool. I can make a quick fix for this one. Would that be alright for me to PR with this change now?

**Comment by nmadruga** [comment]
Although, sorry. I don't  really see where is the problem on the commit you have copied. Maybe it would be better for you to add this PR, and I can review right away : )
