### ISSUE TITLE
Bug: Investigate long time and timeout happening when using MAX_ATTEMPT < 30 on useGetApplicationSerial

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#904]
Seems to be related to time to run generateText to be creating the application name/serial

**Comment by andreievg** [comment]
I've noticed a slow down in docker environment, due to postgres schema query have a `like` match, `getDatabaseInfo`.

I'll add this issue as is fixed in back end PR, but the problem you've described can be from else where.
