### ISSUE TITLE
Bug: Find a nice fix for ugly hack when we need to get just the value from an array

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#908]

**Comment by CarlosNZ** [comment]
Are you talking about evaluator expressions? If so, I made an issue for this last week which I think covers it: https://github.com/openmsupply/application-manager-server/issues/488

**Comment by CarlosNZ** [comment]
We also need a front-end issue to make sure the "type" selector is available in template builder, so maybe convert this issue to that?

**Comment by CarlosNZ** [comment]
This is annoying me a lot, so I'm going to try and fix it today.

**Comment by CarlosNZ** [comment]
Done: https://github.com/openmsupply/application-manager-server/pull/669
