### ISSUE TITLE
Template Builder bug -- "reviewLevel" not being set correctly for Assignment

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/application-manager-web-app#915]
Note the Assignment setting for Stage "Assessment" review level 1:
![Screen Shot 2021-08-18 at 4 55 06 PM](https://user-images.githubusercontent.com/5456533/129839305-b17ef0c4-c100-49c9-9a1e-ea3184c719be.png)

However, when we actually look at the database, the "reviewLevel" is NULL rather than 1:
<img width="1253" alt="Screen Shot 2021-08-18 at 4 57 57 PM" src="https://user-images.githubusercontent.com/5456533/129839515-9358f624-27a4-4681-8233-6867867cf01c.png">

Consequently, no review_assignment_assigner_joins get created when running "generateReviewAssignment", so no one can be assigned in the UI.

**Comment by CarlosNZ** [comment]
@andreievg -- please branch off the last lot of TB fixes you did (or just add it to the same branch if you want)

**Comment by andreievg** [comment]
>  please branch off the last lot of TB fixes you did (or just add it to the same branch if you want)

Ooops, I missed this one, it's in demo and PRed to main
