### ISSUE TITLE
Fix warning about ApplicationViewWrapper of ShortText when the response is null

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#92]
- Go to Register
- Click `User Registration`
- See the error on the console:
![Screen Shot 2020-11-05 at 3 34 33 PM](https://user-images.githubusercontent.com/16461988/98190834-ccf5d200-1f7c-11eb-80b4-79ecf258b7e0.png)

**Comment by CarlosNZ** [comment]
This error seems to have gone away after #109, but now getting this error instead:

<img width="1150" alt="Screen Shot 2020-11-12 at 9 53 27 AM" src="https://user-images.githubusercontent.com/5456533/98863275-01ade000-24cd-11eb-92ca-743f06dcbb48.png">
