### ISSUE TITLE
Refine language used for Company Registration on Dashboard

### ISSUE THREAD

**Issue by adamdewey** [openmsupply/application-manager-web-app#929]
The current language used for the Company Registration is a little odd as the singular and plural versions have been inserted automatically. It's difficult to automate this yet still make sense in English. 

![image](https://user-images.githubusercontent.com/19318937/130562768-e5d205b5-2d69-4ba6-a544-77a248c42015.png)

Suggested update: 

> - Company Registration
> - You don’t have any registered companies yet. 
> - Start a new application

**Comment by CarlosNZ** [comment]
The plural names are quite inconsistent and kind of random for most of the core templates, I was going to tidy them up as I went along.
