### ISSUE TITLE
Change UI: button ‘Back to Company Registration - S-PFW-009’ be amended to ‘View submitted application’

### ISSUE THREAD

**Issue by nmadruga** [openmsupply/application-manager-web-app#955]
See 2nd topic on [comment](https://github.com/openmsupply/application-manager-templates/issues/2#issuecomment-912133466)

![mFlow8](https://user-images.githubusercontent.com/88009219/131929333-2699b749-d1b9-4dd2-a990-8e4e1c4a76b3.png)

**Comment by CarlosNZ** [comment]
That seems like way too much text for a button. Think about how to abbreviate/summarise.

**Comment by nmadruga** [comment]
Yes, good point. As per reply from Jess in [comment](https://github.com/openmsupply/application-manager-templates/issues/2#issuecomment-912168924) I have updated title for this issue
